CREATE TABLE IF NOT EXISTS `neighborhood` (
`ID_neighborhood` int(11) NOT NULL AUTO_INCREMENT
,`descNeighborhood` varchar(70) NOT NULL
, PRIMARY KEY (`ID_neighborhood`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `neighborhood` (`descNeighborhood`) VALUES
('Aclimação'),
('Água Branca'),
('Água Fria'),
('Água Funda'),
('Água Rasa'),
('Alto da Boa Vista'),
('Alto da Lapa'),
('Alto da Moóca'),
('Alto da Riviera'),
('Alto de Pinheiros'),
('Alto do Pari'),
('Altos de Vila Prudente'),
('Americanópolis'),
('Anhangüera'),
('Aricanduva'),
('Artur Alvim'),
('Associação Sobradinho'),
('Balneário Dom Carlos'),
('Balneário Mar Paulista'),
('Balneário São Francisco'),
('Balneário São José'),
('Baronesa'),
('Barra Funda'),
('Barragem'),
('Barro Branco (Zona Norte)'),
('Barro Branco II'),
('Bela Aliança'),
('Bela Vista'),
('Belém'),
('Belenzinho'),
('Boaçava'),
('Bom Retiro'),
('Bororé'),
('Bortolândia'),
('Bosque da Saúde'),
('Brás'),
('Brasilândia'),
('Brooklin Novo'),
('Brooklin Paulista'),
('Burgo Paulista'),
('Butantã'),
('Cachoeirinha'),
('Cambuci'),
('Campininha'),
('Campo Belo'),
('Campo Grande'),
('Campo Limpo'),
('Campos Elíseos'),
('Cangaíba'),
('Canindé'),
('Cantareira'),
('Cantinho do Céu'),
('Capão do Embira'),
('Capão Redondo'),
('Capela do Socorro'),
('Carandiru'),
('Carrão'),
('Casa Grande'),
('Casa Verde'),
('Casa Verde Alta'),
('Casa Verde Baixa'),
('Casa Verde Média'),
('Catumbi'),
('Caxingui'),
('Centro'),
('Cerqueira César'),
('Chácara Bambú'),
('Chácara Bandeirantes'),
('Chácara Belenzinho'),
('Chácara Bosque do Sol'),
('Chácara Califórnia'),
('Chácara Cocaia'),
('Chácara Cruzeiro do Sul'),
('Chácara da Enseada'),
('Chácara das Corujas'),
('Chácara das Palmeiras'),
('Chácara do Conde'),
('Chácara do Encosto'),
('Chácara do Sol'),
('Chácara Dona Olívia'),
('Chácara Figueira Grande'),
('Chácara Flora'),
('Chácara Flórida'),
('Chácara Gaivotas'),
('Chácara Inglesa'),
('Chácara Itaim'),
('Chácara Japonesa'),
('Chácara Jaraguá'),
('Chácara Mafalda'),
('Chácara Maria Trindade'),
('Chácara Meyer'),
('Chácara Monte Alegre'),
('Chácara Monte Sol'),
('Chácara Morro Alto'),
('Chácara Nani'),
('Chácara Nossa Senhora Aparecida'),
('Chácara Nossa Senhora do Bom Conselho'),
('Chácara Paiva'),
('Chácara Pirajussara'),
('Chácara Pouso Alegre'),
('Chácara Santa Etelvina'),
('Chácara Santa Maria'),
('Chácara Santana'),
('Chácara Santo Amaro'),
('Chácara Santo Antônio (Zona Leste)'),
('Chácara Santo Antônio (Zona Sul)'),
('Chácara Santo Hubertus'),
('Chácara São João'),
('Chácara São Luís'),
('Chácara São Silvestre'),
('Chácara Seis de Outubro'),
('Chácara Sonho Azul'),
('Chácara Tatuapé'),
('Chácara Três Meninas'),
('Chácara Vista Alegre'),
('Chácara Vovo'),
('Chácaras Lago Grande'),
('Chapada'),
('Chora Menino'),
('Cidade Ademar'),
('Cidade Antônio Estevão de Carvalho'),
('Cidade Auxiliadora'),
('Cidade Centenário'),
('Cidade Continental'),
('Cidade D\'Abril'),
('Cidade Domitila'),
('Cidade dos Bandeirantes'),
('Cidade Dutra'),
('Cidade Fim de Semana'),
('Cidade Ipava'),
('Cidade Jardim'),
('Cidade Júlia'),
('Cidade Kemel'),
('Cidade Leonor'),
('Cidade Líder'),
('Cidade Luz'),
('Cidade Mãe do Céu'),
('Cidade Monções'),
('Cidade Munhoz Junior'),
('Cidade Nautica'),
('Cidade Nitro Operária'),
('Cidade Nitro Química'),
('Cidade Nova América'),
('Cidade Nova Heliópolis'),
('Cidade Nova São Miguel'),
('Cidade Patriarca'),
('Cidade Popular'),
('Cidade São Francisco'),
('Cidade São Mateus'),
('Cidade São Miguel'),
('Cidade Satelite'),
('Cidade Satélite Santa Bárbara'),
('Cidade Tiradentes'),
('Cidade Vargas'),
('Cipó do Meio'),
('City América'),
('Clube Campestre de São Paulo'),
('Clube dos Funcionários Públicos Colônia'),
('Cohab Monet'),
('Colônia (Zona Leste)'),
('Colônia (Zona Sul)'),
('Condomínio Jequirituba'),
('Condomínio São Marcos'),
('Conjunto City Jaraguá'),
('Conjunto dos Bancários'),
('Conjunto Habitacional A E Carvalho'),
('Conjunto Habitacional Águia de Haia'),
('Conjunto Habitacional Barreira Grande'),
('Conjunto Habitacional Barro Branco I'),
('Conjunto Habitacional Barro Branco II'),
('Conjunto Habitacional Brigadeiro Eduardo Gomes'),
('Conjunto Habitacional Brigadeiro Faria Lima'),
('Conjunto Habitacional Castro Alves'),
('Conjunto Habitacional Fazenda do Carmo'),
('Conjunto Habitacional Inácio Monteiro'),
('Conjunto Habitacional Instituto Adventista'),
('Conjunto Habitacional Jardim São Bento'),
('Conjunto Habitacional Jardim São Francisco'),
('Conjunto Habitacional Jova Rural'),
('Conjunto Habitacional Juscelino Kubitschek'),
('Conjunto Habitacional Marechal Mascarenhas de Morais'),
('Conjunto Habitacional Padre José de Anchieta'),
('Conjunto Habitacional Padre Manoel da Nóbrega'),
('Conjunto Habitacional Padre Manoel de Paiva'),
('Conjunto Habitacional Parque Valo Velho II'),
('Conjunto Habitacional Pirajussara'),
('Conjunto Habitacional Recanto dos Humildes'),
('Conjunto Habitacional Santa Etelvina I'),
('Conjunto Habitacional Santa Etelvina II'),
('Conjunto Habitacional Santa Etelvina III'),
('Conjunto Habitacional Sitio Caraguata'),
('Conjunto Habitacional Sitio Conceição'),
('Conjunto Habitacional Teotonio Vilela'),
('Conjunto Habitacional Turística'),
('Conjunto Habitacional Vila Nova Cachoeirinha'),
('Conjunto Promorar Estrada da Parada'),
('Conjunto Promorar Raposo Tavares'),
('Conjunto Promorar Rio Claro'),
('Conjunto Promorar São Luis'),
('Conjunto Promorar Sapopemba'),
('Conjunto Promorar Vila Maria III'),
('Conjunto Residencial Alpes do Jaraguá'),
('Conjunto Residencial Bandeirantes'),
('Conjunto Residencial Butantã'),
('Conjunto Residencial Elisio Teixeira Leite'),
('Conjunto Residencial Ingai'),
('Conjunto Residencial Jardim Canaã'),
('Conjunto Residencial José Bonifácio'),
('Conjunto Residencial Morumbi'),
('Conjunto Residencial Novo Pacaembu'),
('Conjunto Residencial Paraíso'),
('Conjunto Residencial Pinheirinho'),
('Conjunto Residencial Prestes Maia'),
('Conjunto Residencial Sabará - Campo Grande'),
('Conjunto Residencial Salvador Tolezani'),
('Conjunto Residencial Santa Maria'),
('Conjunto Residencial Santa Terezinha'),
('Conjunto Residencial Sitio Oratório'),
('Conjunto Residencial Vista Verde'),
('Consolação'),
('Copacabana'),
('Cupecê'),
('Cursino'),
('Educandário'),
('Eldorado'),
('Embu Mirim'),
('Embura'),
('Engenheiro Goulart'),
('Engenheiro Marsilac'),
('Engenheiro Trindade'),
('Ermelino Matarazzo'),
('Estância Jaraguá'),
('Estância Mirim'),
('Estância Tangara'),
('Favela Vila Nova Jaguaré'),
('Fazenda Aricanduva'),
('Fazenda Caguaçu'),
('Fazenda da Juta'),
('Fazenda Itaim'),
('Fazenda Morumbi'),
('Ferreira'),
('Flor da Cantareira'),
('Freguesia do Ó'),
('Furnas'),
('Gleba do Pêssego'),
('Grajaú'),
('Gramado'),
('Granja Julieta'),
('Granja Nossa Senhora Aparecida'),
('Guacuri'),
('Guaianazes'),
('Guaiaúna'),
('Guapira'),
('Guarapiranga'),
('Guavirutuba'),
('Higienópolis'),
('Horto'),
('Horto Florestal'),
('Ibirapuera'),
('Iguatemi'),
('Imirim'),
('Indianópolis'),
('Instituto de Previdência'),
('Interlagos'),
('Ipiranga'),
('Itaberaba'),
('Itaim'),
('Itaim Bibi'),
('Itaim Paulista'),
('Itaquera'),
('Itupu'),
('Jabaquara'),
('Jaçanã'),
('Jaguaré'),
('Jaraguá'),
('Jardim Adelaide'),
('Jardim Adelfiore'),
('Jardim Adélia'),
('Jardim Adhemar de Barros'),
('Jardim Adutora'),
('Jardim Aeroporto'),
('Jardim Aida'),
('Jardim Aimoré'),
('Jardim Aladim'),
('Jardim Alfredo'),
('Jardim Almanara'),
('Jardim Almeida'),
('Jardim Almeida Prado'),
('Jardim Alpino'),
('Jardim Alteza'),
('Jardim Alto Alegre (São Rafael)'),
('Jardim Alto Alegre (Zona Leste)'),
('Jardim Alto do Rio Bonito'),
('Jardim Alto Paulistano'),
('Jardim Alto Pedroso'),
('Jardim Alva'),
('Jardim Alvarenga'),
('Jardim Alvina'),
('Jardim Alviverde'),
('Jardim Alvorada (Zona Norte)'),
('Jardim Alvorada (Zona Oeste)'),
('Jardim Alvorada (Zona Sul)'),
('Jardim Alzira'),
('Jardim Amália'),
('Jardim Amaralina'),
('Jardim América'),
('Jardim América da Penha'),
('Jardim Ampliação'),
('Jardim Ana Lúcia'),
('Jardim Ana Maria'),
('Jardim Ana Rosa'),
('Jardim Anália Franco'),
('Jardim Anchieta'),
('Jardim Andaraí'),
('Jardim Ângela (Zona Leste)'),
('Jardim Ângela (Zona Sul)'),
('Jardim Angelina'),
('Jardim Anhangüera'),
('Jardim Antártica'),
('Jardim Aparecida'),
('Jardim Apuana'),
('Jardim Apurá'),
('Jardim Aracati'),
('Jardim Arantes'),
('Jardim Arco-Iris'),
('Jardim Aricanduva'),
('Jardim Aristocrata'),
('Jardim Arize'),
('Jardim Arizona'),
('Jardim Arpoador'),
('Jardim Artur Alvim'),
('Jardim Assunção'),
('Jardim Ataliba Leonel'),
('Jardim Atibaia'),
('Jardim Atlântico'),
('Jardim Augusta'),
('Jardim Augusto'),
('Jardim Áurea'),
('Jardim Aurélia'),
('Jardim Aurélio'),
('Jardim Aurora (Zona Leste)'),
('Jardim Aurora (Zona Oeste)'),
('Jardim Avelino'),
('Jardim Avenida'),
('Jardim Azano I'),
('Jardim Azano II'),
('Jardim Bandeirante'),
('Jardim Bandeirante (São Rafael)'),
('Jardim Bandeirantes'),
('Jardim Bandeirantes (Zona Norte)'),
('Jardim Bárbara'),
('Jardim Barros'),
('Jardim Bartira'),
('Jardim Batalha'),
('Jardim Beatriz'),
('Jardim Beatriz (Zona Leste)'),
('Jardim Bela Vista (Zona Norte)'),
('Jardim Bela Vista (Zona Sul)'),
('Jardim Belaura'),
('Jardim Belcito'),
('Jardim Belém'),
('Jardim Bélgica'),
('Jardim Benfica'),
('Jardim Bibi'),
('Jardim Bichinhos'),
('Jardim Boa Esperança'),
('Jardim Boa Sorte'),
('Jardim Boa Vista (Zona Oeste)'),
('Jardim Boa Vista (Zona Sul)'),
('Jardim Bom Clima'),
('Jardim Bom Pastor'),
('Jardim Bom Refúgio'),
('Jardim Bonfiglioli'),
('Jardim Bonito'),
('Jardim Borba Gato'),
('Jardim Bosque do Sol'),
('Jardim Botucatu'),
('Jardim Brasil (Zona Norte)'),
('Jardim Brasil (Zona Sul)'),
('Jardim Brasil Novo'),
('Jardim Brasília'),
('Jardim Brasília (Zona Leste)'),
('Jardim Brasília (Zona Norte)'),
('Jardim Britânia'),
('Jardim Bronzato'),
('Jardim Buriti'),
('Jardim Caboré'),
('Jardim Cabuçu'),
('Jardim Cachoeira'),
('Jardim Caguassu'),
('Jardim Camara'),
('Jardim Camargo Novo'),
('Jardim Cambara'),
('Jardim Campinas'),
('Jardim Campo dos Ferreiros'),
('Jardim Campo Grande'),
('Jardim Campo Limpo'),
('Jardim Campo Limpo (Zona Norte)'),
('Jardim Campos'),
('Jardim Capão Redondo'),
('Jardim Capela'),
('Jardim Capelinha'),
('Jardim Caravelas'),
('Jardim Carlu'),
('Jardim Carolina'),
('Jardim Carombé'),
('Jardim Casa Grande'),
('Jardim Casa Pintada'),
('Jardim Casablanca'),
('Jardim Castelo'),
('Jardim Castro Alves'),
('Jardim Catanduva'),
('Jardim Catarina'),
('Jardim Cecy'),
('Jardim Cedro do Líbano'),
('Jardim Celeste'),
('Jardim Célia'),
('Jardim Centenário'),
('Jardim Central'),
('Jardim Cercado da Estrada'),
('Jardim Chester'),
('Jardim Cibele'),
('Jardim Cidade Pirituba'),
('Jardim Cidália'),
('Jardim Cimobil'),
('Jardim Cinco de Julho'),
('Jardim Clara Regina'),
('Jardim Clarice'),
('Jardim Cláudia'),
('Jardim Cleide'),
('Jardim Clélia'),
('Jardim Clímax'),
('Jardim Cliper'),
('Jardim Coimbra'),
('Jardim Colina'),
('Jardim Colombo'),
('Jardim Colonial'),
('Jardim Colorado'),
('Jardim Comercial'),
('Jardim Concórdia'),
('Jardim Consórcio'),
('Jardim Consupler'),
('Jardim Copacabana'),
('Jardim Cordeiro'),
('Jardim Corisco'),
('Jardim Cotching'),
('Jardim Cotiana'),
('Jardim Cotinha'),
('Jardim Cristal'),
('Jardim Cristália'),
('Jardim Cristina'),
('Jardim Cruzeiro'),
('Jardim Cupecê'),
('Jardim D\'Abril'),
('Jardim da Cachoeira'),
('Jardim da Campina'),
('Jardim da Conquista (Zona Leste)'),
('Jardim da Conquista (Zona Oeste)'),
('Jardim da Glória'),
('Jardim da Laranjeira (Zona Leste)'),
('Jardim da Pedreira'),
('Jardim da Saúde'),
('Jardim Dalmo'),
('Jardim Damasceno'),
('Jardim Danfer'),
('Jardim Danubio Azul'),
('Jardim das Acácias'),
('Jardim das Bandeiras'),
('Jardim das Camélias'),
('Jardim das Camélias (Zona Sul)'),
('Jardim das Esmeraldas'),
('Jardim das Flores'),
('Jardim das Fontes'),
('Jardim das Graças'),
('Jardim das Imbuias'),
('Jardim das Laranjeiras'),
('Jardim das Laranjeiras (Zona Sul)'),
('Jardim das Oliveiras'),
('Jardim das Oliveiras (Zona Sul)'),
('Jardim das Palmas'),
('Jardim das Palmeiras'),
('Jardim das Palmeiras (Zona Sul)'),
('Jardim das Pedras'),
('Jardim das Pedras(Zona Sul)'),
('Jardim das Praias'),
('Jardim das Rosas (Iguatemi)'),
('Jardim das Rosas (Zona Leste I)'),
('Jardim das Rosas (Zona Norte)'),
('Jardim das Rosas (Zona Sul)'),
('Jardim das Vertentes'),
('Jardim Daysy'),
('Jardim de Lorenzo'),
('Jardim Denise'),
('Jardim Denyse'),
('Jardim Deolinda'),
('Jardim Dinar'),
('Jardim Dinorah'),
('Jardim Diomar'),
('Jardim Dionisio'),
('Jardim do Alto'),
('Jardim do Campo'),
('Jardim do Carmo'),
('Jardim do Centro'),
('Jardim do Colégio'),
('Jardim do Colégio (Zona Norte)'),
('Jardim do Divino'),
('Jardim do Lago'),
('Jardim do Russo'),
('Jardim do Sol'),
('Jardim do Tiro'),
('Jardim Dom Bosco'),
('Jardim Dom Fernando'),
('Jardim Dom José'),
('Jardim Domitila'),
('Jardim Dona Deolinda'),
('Jardim Dona Sinhá'),
('Jardim Donária'),
('Jardim dos Álamos'),
('Jardim dos Bichinhos'),
('Jardim dos Cataldis'),
('Jardim dos Estados'),
('Jardim dos Eucaliptos'),
('Jardim dos Francos'),
('Jardim dos Ipês'),
('Jardim dos Jacarandás'),
('Jardim dos Lagos'),
('Jardim dos Manacás'),
('Jardim dos Pereiras'),
('Jardim dos Pinheiros'),
('Jardim dos Prados'),
('Jardim Dracena'),
('Jardim Drumond'),
('Jardim Duprat'),
('Jardim Edda'),
('Jardim Edi'),
('Jardim Edilene'),
('Jardim Edith'),
('Jardim Edwiges'),
('Jardim Egle'),
('Jardim Elba'),
('Jardim Eledy'),
('Jardim Eliana'),
('Jardim Eliane'),
('Jardim Elisa Maria'),
('Jardim Elisio'),
('Jardim Eliza'),
('Jardim Elizabeth'),
('Jardim Ellus'),
('Jardim Elza'),
('Jardim Emilia'),
('Jardim Engenheiro Visconti'),
('Jardim Ernestina'),
('Jardim Esmeralda'),
('Jardim Esmeralda (Zona Sul)'),
('Jardim Esperança'),
('Jardim Ester'),
('Jardim Ester Yolanda'),
('Jardim Estrela'),
('Jardim Estrela D\'alva'),
('Jardim Etelvina'),
('Jardim Europa'),
('Jardim Eva'),
('Jardim Everest'),
('Jardim Fanganiello'),
('Jardim Faria Lima'),
('Jardim Felicidade (Zona Norte)'),
('Jardim Felicidade (Zona Oeste)'),
('Jardim Fernandes'),
('Jardim Figueira Grande'),
('Jardim Filhos da Terra'),
('Jardim Fim de Semana'),
('Jardim Flamingo'),
('Jardim Flor de Maio'),
('Jardim Floresta'),
('Jardim Flórida Paulista'),
('Jardim Fluminense'),
('Jardim Fontalis'),
('Jardim Fonte do Morumbi'),
('Jardim Fonte São Miguel'),
('Jardim Franca'),
('Jardim Francisco Mendes'),
('Jardim Francisco Mentem'),
('Jardim Franganielo'),
('Jardim Fraternidade'),
('Jardim Fujihara'),
('Jardim Galli'),
('Jardim Germânia'),
('Jardim Gianetti'),
('Jardim Gilberto'),
('Jardim Gilda Maria'),
('Jardim Glória'),
('Jardim Gonzaga'),
('Jardim Grimaldi'),
('Jardim Guacuri'),
('Jardim Guaianazes'),
('Jardim Guairaca'),
('Jardim Guanabara'),
('Jardim Guanca'),
('Jardim Guanhembu'),
('Jardim Guapira'),
('Jardim Guarani'),
('Jardim Guarapiranga'),
('Jardim Guarau'),
('Jardim Guarujá'),
('Jardim Guedala'),
('Jardim Guiomar'),
('Jardim Gustavo'),
('Jardim Hadad'),
('Jardim Haia do Carrão'),
('Jardim Harmonia'),
('Jardim Hebrom'),
('Jardim Helena'),
('Jardim Helga'),
('Jardim Heliomar'),
('Jardim Heloisa'),
('Jardim Hercilia'),
('Jardim Herculano'),
('Jardim Herplin'),
('Jardim Hípico'),
('Jardim Horizonte Azul'),
('Jardim Horto Florestal'),
('Jardim Humaitá'),
('Jardim Humberto Nastari'),
('Jardim Iae'),
('Jardim Iara'),
('Jardim Ibirapuera'),
('Jardim Ibiratiba'),
('Jardim Ibitirama'),
('Jardim Icara'),
('Jardim Icaraí'),
('Jardim Ida Guedes'),
('Jardim Ideal'),
('Jardim Iguatemi'),
('Jardim Imbé'),
('Jardim Imperador (Zona Leste)'),
('Jardim Imperador (Zona Sul)'),
('Jardim Imperial'),
('Jardim Império'),
('Jardim Indaiá'),
('Jardim Independência'),
('Jardim Ingá'),
('Jardim Internacional'),
('Jardim Ipanema (Cidade Líder)'),
('Jardim Ipanema (São Miguel)'),
('Jardim Ipanema (Zona Oeste)'),
('Jardim Ipanema (Zona Sul)'),
('Jardim Ipê'),
('Jardim Iporã'),
('Jardim Iporanga'),
('Jardim Iracema'),
('Jardim Irapiranga'),
('Jardim Irene'),
('Jardim Íris'),
('Jardim Itacolomi'),
('Jardim Itajai'),
('Jardim Itália'),
('Jardim Itamaraty'),
('Jardim Itaoca'),
('Jardim Itapema'),
('Jardim Itapemirim'),
('Jardim Itapeva'),
('Jardim Itápolis'),
('Jardim Itapura'),
('Jardim Itatiaia'),
('Jardim Itatinga'),
('Jardim Iva'),
('Jardim Ivana'),
('Jardim Ivete'),
('Jardim Ivone'),
('Jardim Jabaquara'),
('Jardim Jaçanã'),
('Jardim Jamaica'),
('Jardim Japão'),
('Jardim Jaqueline'),
('Jardim Jaraguá'),
('Jardim Jaraguá (Itaim Paulista)'),
('Jardim Jaraguá (São Domingos)'),
('Jardim Jaú (Zona Leste)'),
('Jardim Jaú (Zona Sul)'),
('Jardim Jeriva'),
('Jardim Joamar'),
('Jardim Joana D\'Arc'),
('Jardim João XXIII'),
('Jardim Jordão'),
('Jardim Jua'),
('Jardim Julieta'),
('Jardim Jurema'),
('Jardim Jussara'),
('Jardim Kagohara'),
('Jardim Kaj'),
('Jardim Keralux'),
('Jardim Kika'),
('Jardim Kioto'),
('Jardim Labitary'),
('Jardim Lajeado'),
('Jardim Lallo'),
('Jardim Laone'),
('Jardim Lapena'),
('Jardim Lar São Paulo'),
('Jardim Laranjal'),
('Jardim Laranjeiras'),
('Jardim Laura'),
('Jardim Leila'),
('Jardim Leme'),
('Jardim Leni'),
('Jardim Leonardo'),
('Jardim Leônidas Moreira'),
('Jardim Leonor'),
('Jardim Leonor Mendes de Barros'),
('Jardim Letícia'),
('Jardim Líbano'),
('Jardim Lice'),
('Jardim Lider'),
('Jardim Liderança'),
('Jardim Lídia'),
('Jardim Lilah'),
('Jardim Limoeiro'),
('Jardim Lisboa'),
('Jardim Londrina'),
('Jardim Los Angeles'),
('Jardim Lourdes'),
('Jardim Lourdes (Zona Sul)'),
('Jardim Luanda'),
('Jardim Lucélia'),
('Jardim Lúcia'),
('Jardim Luciana'),
('Jardim Lucinda'),
('Jardim Lúcio de Castro'),
('Jardim Lugo'),
('Jardim Luísa'),
('Jardim Luso'),
('Jardim Luzitânia'),
('Jardim Mabel'),
('Jardim Macedônia'),
('Jardim Machado'),
('Jardim Maggi'),
('Jardim Maia'),
('Jardim Mália I'),
('Jardim Mália II'),
('Jardim Mangalot'),
('Jardim Mar Lune'),
('Jardim Marabá'),
('Jardim Marabá(Zona Sul)'),
('Jardim Maracá'),
('Jardim Maracanã'),
('Jardim Marajoara'),
('Jardim Marcel'),
('Jardim Marcelo'),
('Jardim Marciano'),
('Jardim Marco Paulo'),
('Jardim Margarida'),
('Jardim Maria Amália'),
('Jardim Maria Augusta'),
('Jardim Maria Duarte'),
('Jardim Maria Emília'),
('Jardim Maria Estela'),
('Jardim Maria Fernandes'),
('Jardim Maria Lídia'),
('Jardim Maria Lúcia'),
('Jardim Maria Luiza'),
('Jardim Maria Margarida'),
('Jardim Maria Nazaré'),
('Jardim Maria Rita'),
('Jardim Maria Sampaio'),
('Jardim Maria Virginia'),
('Jardim Mariane'),
('Jardim Marilda'),
('Jardim Marília'),
('Jardim Mariliza'),
('Jardim Marilu'),
('Jardim Marina'),
('Jardim Maringá'),
('Jardim Marisa'),
('Jardim Maristela'),
('Jardim Marpu'),
('Jardim Marquesa'),
('Jardim Martha'),
('Jardim Martini'),
('Jardim Martinica'),
('Jardim Martins Silva'),
('Jardim Mascarenhas'),
('Jardim Matarazzo'),
('Jardim Mazza'),
('Jardim Meliunas'),
('Jardim Melo'),
('Jardim Mikail'),
('Jardim Mimar'),
('Jardim Miragaia'),
('Jardim Mirante'),
('Jardim Miriam'),
('Jardim Mitsutani'),
('Jardim Modelo'),
('Jardim Mônica'),
('Jardim Monjolo'),
('Jardim Monte Alegre'),
('Jardim Monte Alegre (Zona Norte)'),
('Jardim Monte Azul'),
('Jardim Monte Belo'),
('Jardim Monte Belo (Raposo Tavares)'),
('Jardim Monte Kemel'),
('Jardim Monte Verde'),
('Jardim Morais Prado'),
('Jardim Moreno'),
('Jardim Morganti'),
('Jardim Morro Verde'),
('Jardim Morumbi'),
('Jardim Mutinga'),
('Jardim Myrna'),
('Jardim Myrna II'),
('Jardim Nadir'),
('Jardim Nagib Salem'),
('Jardim Nair'),
('Jardim Nakamura'),
('Jardim Namba'),
('Jardim Nardini'),
('Jardim Nastari'),
('Jardim Natal'),
('Jardim Naufal'),
('Jardim Nazareth'),
('Jardim Neide'),
('Jardim Neila'),
('Jardim Nélia'),
('Jardim Nelia IV'),
('Jardim Nelly'),
('Jardim Nice'),
('Jardim Niteroi'),
('Jardim Nizia'),
('Jardim Noemia'),
('Jardim Nordeste'),
('Jardim Norma'),
('Jardim Noronha'),
('Jardim Nossa Senhora Aparecida'),
('Jardim Nossa Senhora do Carmo'),
('Jardim Nosso Lar'),
('Jardim Nova Brasília'),
('Jardim Nova Colonia'),
('Jardim Nova Germania'),
('Jardim Nova Guaianazes'),
('Jardim Nova Harmonia'),
('Jardim Nova Tereza'),
('Jardim Nova Vitória I'),
('Jardim Nova Vitória II'),
('Jardim Nove de Julho'),
('Jardim Novo Carrão'),
('Jardim Novo Horizonte'),
('Jardim Novo Jaú'),
('Jardim Novo Lar'),
('Jardim Novo Mundo'),
('Jardim Novo Parelheiros'),
('Jardim Novo Santo Amaro'),
('Jardim Novo Taboão'),
('Jardim Odete'),
('Jardim Olinda'),
('Jardim Olympia'),
('Jardim Ondina'),
('Jardim Orbam'),
('Jardim Oriental'),
('Jardim Oriental (Parelheiros)'),
('Jardim Orion'),
('Jardim Orly'),
('Jardim Ormendina'),
('Jardim Outono'),
('Jardim Palmares (Zona Norte)'),
('Jardim Palmares (Zona Sul)'),
('Jardim Panorama'),
('Jardim Panorama (Zona Leste)'),
('Jardim Panorama (Zona Sul)'),
('Jardim Panorama D\'Oeste'),
('Jardim Pantanal'),
('Jardim Papai Noel'),
('Jardim Paquetá (Zona Norte)'),
('Jardim Paquetá (Zona Sul)'),
('Jardim Pará'),
('Jardim Paraguaçu'),
('Jardim Paraíso'),
('Jardim Paris'),
('Jardim Parque Morumbi'),
('Jardim Patente'),
('Jardim Patente Novo'),
('Jardim Pauliceia'),
('Jardim Paulista'),
('Jardim Paulistano'),
('Jardim Paulistano (Zona Norte)'),
('Jardim Paulo Afonso'),
('Jardim Paulo Borba'),
('Jardim Paulo VI'),
('Jardim Pedra Branca'),
('Jardim Pedra Branca II'),
('Jardim Pedro José Nunes'),
('Jardim Penha'),
('Jardim Pereira Leite'),
('Jardim Peri'),
('Jardim Peri Novo'),
('Jardim Peri Peri'),
('Jardim Pérola I'),
('Jardim Pérola II'),
('Jardim Pérola III'),
('Jardim Perus'),
('Jardim Petisco'),
('Jardim Petrópolis'),
('Jardim Picolo'),
('Jardim Pinheiros'),
('Jardim Piqueri'),
('Jardim Piqueroby'),
('Jardim Piracema'),
('Jardim Piracuama'),
('Jardim Pirajussara'),
('Jardim Piratininga'),
('Jardim Pirituba'),
('Jardim Planalto'),
('Jardim Poleti'),
('Jardim Pongilutti'),
('Jardim Ponte Rasa'),
('Jardim Popular'),
('Jardim Portal I e II'),
('Jardim Porteira Grande'),
('Jardim Pouso Alegre'),
('Jardim Prainha'),
('Jardim Presidente'),
('Jardim Previdência'),
('Jardim Primavera'),
('Jardim Princesa'),
('Jardim Progresso'),
('Jardim Promissão'),
('Jardim Prudência'),
('Jardim Quarto Centenário'),
('Jardim Quisisana (Vila Nova Curuçá)'),
('Jardim Ramala'),
('Jardim Raposo Tavares'),
('Jardim Real'),
('Jardim Recanto do Sol'),
('Jardim Recanto Verde'),
('Jardim Record'),
('Jardim Recreio'),
('Jardim Redenção'),
('Jardim Redil'),
('Jardim Regina'),
('Jardim Regis'),
('Jardim Reimberg'),
('Jardim Remo'),
('Jardim Represa'),
('Jardim Represa (Parelheiros)'),
('Jardim República'),
('Jardim Ricardo'),
('Jardim Rincão'),
('Jardim Rio Bonito'),
('Jardim Rio Douro'),
('Jardim Rio Pequeno'),
('Jardim Riviera'),
('Jardim Rizzo'),
('Jardim Robru'),
('Jardim Rodolfo Pirani'),
('Jardim Romano'),
('Jardim Roni'),
('Jardim Rosa Maria'),
('Jardim Rosalina'),
('Jardim Rosana'),
('Jardim Roschel'),
('Jardim Roseli'),
('Jardim Rosider'),
('Jardim Rosina'),
('Jardim Rosinha'),
('Jardim Rossin'),
('Jardim Rubilene'),
('Jardim Rubio'),
('Jardim Russo'),
('Jardim Ruth'),
('Jardim S Kemel'),
('Jardim Sabará'),
('Jardim Sabiá'),
('Jardim Sabiá II'),
('Jardim Sagrado Coração'),
('Jardim Samambaia'),
('Jardim Samara'),
('Jardim Samas'),
('Jardim Sandra'),
('Jardim Sandra Maria'),
('Jardim Santa Adélia'),
('Jardim Santa Bárbara'),
('Jardim Santa Branca'),
('Jardim Santa Cecília'),
('Jardim Santa Cruz (Campo Grande)'),
('Jardim Santa Cruz (Parelheiros)'),
('Jardim Santa Cruz (Sacomã)'),
('Jardim Santa Cruz (Zona Norte)'),
('Jardim Santa Edwiges (Capela do Socorro)'),
('Jardim Santa Edwiges (Grajaú)'),
('Jardim Santa Efigênia'),
('Jardim Santa Emília'),
('Jardim Santa Etelvina'),
('Jardim Santa Fé (Zona Oeste)'),
('Jardim Santa Fé (Zona Sul)'),
('Jardim Santa Filomena'),
('Jardim Santa Francisca Cabrini'),
('Jardim Santa Gertrudes'),
('Jardim Santa Helena'),
('Jardim Santa Inês'),
('Jardim Santa Josefina'),
('Jardim Santa Lucrécia'),
('Jardim Santa Luísa'),
('Jardim Santa Marcelina'),
('Jardim Santa Margarida'),
('Jardim Santa Maria'),
('Jardim Santa Mônica'),
('Jardim Santa Rita'),
('Jardim Santa Tereza'),
('Jardim Santa Terezinha'),
('Jardim Santa Terezinha (Parelheiros)'),
('Jardim Santa Terezinha (Pedreira)'),
('Jardim Santa Terezinha (Zona Leste)'),
('Jardim Santa Zélia'),
('Jardim Santana'),
('Jardim Santo Alberto'),
('Jardim Santo Amaro'),
('Jardim Santo André'),
('Jardim Santo Antoninho'),
('Jardim Santo Antônio'),
('Jardim Santo Elias'),
('Jardim Santo Elias (São Miguel)'),
('Jardim Santo Onofre'),
('Jardim Santos Dumont'),
('Jardim São Benedito'),
('Jardim São Bento'),
('Jardim São Bento Novo'),
('Jardim São Bernardo'),
('Jardim São Carlos (Zona Leste)'),
('Jardim São Carlos (Zona Sul)'),
('Jardim São Cristóvão'),
('Jardim São Domingos'),
('Jardim São Francisco'),
('Jardim São Francisco (Parelheiros)'),
('Jardim São Francisco (Zona Leste)'),
('Jardim São Francisco de Assis'),
('Jardim São Francisco(Zona Sul)'),
('Jardim São Gabriel'),
('Jardim São Gilberto'),
('Jardim São Gonçalo'),
('Jardim São Januário'),
('Jardim São João'),
('Jardim São João (Guaianazes)'),
('Jardim São João (Jaraguá)'),
('Jardim São João (São Rafael)'),
('Jardim São João (Zona Leste)'),
('Jardim São João (Zona Norte)'),
('Jardim São Joaquim'),
('Jardim São Jorge'),
('Jardim São José'),
('Jardim São José (Artur Alvim)'),
('Jardim São José (São Mateus)'),
('Jardim São José (Zona Norte)'),
('Jardim São José (Zona Sul)'),
('Jardim São Judas Tadeu'),
('Jardim São Lourenço'),
('Jardim São Luís'),
('Jardim São Luís (Zona Leste)'),
('Jardim São Luís (Zona Norte)'),
('Jardim São Manoel'),
('Jardim São Martinho'),
('Jardim São Mateus'),
('Jardim São Miguel'),
('Jardim São Nicolau'),
('Jardim São Norberto'),
('Jardim São Paulo(Zona Leste)'),
('Jardim São Paulo(Zona Norte)'),
('Jardim São Pedro'),
('Jardim São Pedro (Zona Sul)'),
('Jardim São Rafael'),
('Jardim São Raimundo'),
('Jardim São Remo'),
('Jardim São Ricardo'),
('Jardim São Roberto'),
('Jardim São Roque'),
('Jardim São Savério'),
('Jardim São Sebastião'),
('Jardim São Silvestre'),
('Jardim São Vicente'),
('Jardim São Vitor'),
('Jardim Sapopemba'),
('Jardim Sarah'),
('Jardim Satélite'),
('Jardim Saúde'),
('Jardim Scaff'),
('Jardim Seckler'),
('Jardim Selma'),
('Jardim Senice'),
('Jardim Sertãozinho'),
('Jardim Sete de Setembro'),
('Jardim Shangrilá (Zona Norte)'),
('Jardim Shangrilá (Zona Sul)'),
('Jardim Silva Teles'),
('Jardim Silveira'),
('Jardim Sílvia (Zona Leste)'),
('Jardim Sílvia (Zona Oeste)'),
('Jardim Sipramar'),
('Jardim Soares'),
('Jardim Solange'),
('Jardim Somara'),
('Jardim Sônia (Zona Sul)'),
('Jardim Sônia Inga'),
('Jardim Sonia Marly'),
('Jardim Sônia Regina'),
('Jardim Soraia'),
('Jardim Souza'),
('Jardim Sul São Paulo'),
('Jardim Suzana'),
('Jardim Sydney'),
('Jardim Taboão'),
('Jardim Taipas'),
('Jardim Tamoio'),
('Jardim Tanay'),
('Jardim Tango'),
('Jardim Tapera'),
('Jardim Taquaral'),
('Jardim Teixeira'),
('Jardim Tenani'),
('Jardim Teresa'),
('Jardim Teresa Cristina'),
('Jardim Textil'),
('Jardim Thealia'),
('Jardim Thomaz'),
('Jardim Tietê'),
('Jardim Tiro ao Pombo'),
('Jardim Toca'),
('Jardim Tremembé'),
('Jardim Três Corações'),
('Jardim Três Marias'),
('Jardim Triana'),
('Jardim Tricolor'),
('Jardim Tropical'),
('Jardim Trussardi'),
('Jardim Tuã'),
('Jardim Tupã'),
('Jardim Tupi'),
('Jardim Turquesa'),
('Jardim Uberaba'),
('Jardim Ubirajara (Zona Leste)'),
('Jardim Ubirajara (Zona Sul)'),
('Jardim Uirapuru'),
('Jardim Umarizal'),
('Jardim Umuarama'),
('Jardim União'),
('Jardim Uniserve'),
('Jardim Universal'),
('Jardim Universidade Pinheiros'),
('Jardim Universitário'),
('Jardim Vale das Virtudes'),
('Jardim Vale do Ribeira'),
('Jardim Vale do Sol'),
('Jardim Valparaiso'),
('Jardim Valquiria'),
('Jardim Varginha'),
('Jardim Vaz de Lima'),
('Jardim Vazani'),
('Jardim Vera Cruz'),
('Jardim Vera Cruz (Parelheiros)'),
('Jardim Vera Cruz(Zona Leste)'),
('Jardim Vera Cruz(Zona Sul)'),
('Jardim Vergueiro'),
('Jardim Vergueiro (Sacomã)'),
('Jardim Verônia'),
('Jardim Viana'),
('Jardim Vieira'),
('Jardim Vila Carrão'),
('Jardim Vila Formosa'),
('Jardim Vila Mariana'),
('Jardim Vila Nova Progresso'),
('Jardim Vila Rica'),
('Jardim Vilas Boas'),
('Jardim Vilma'),
('Jardim Virginia'),
('Jardim Virginia Bianca'),
('Jardim Vista Alegre'),
('Jardim Vista Linda'),
('Jardim Vitória'),
('Jardim Vitória Régia'),
('Jardim Vitória Régia (Zona Norte)'),
('Jardim Vivan'),
('Jardim Wanda'),
('Jardim Wilma Flor'),
('Jardim Yara'),
('Jardim Ymay'),
('Jardim Zaira'),
('Jardim Zelia'),
('Jardim Zilda'),
('Jardins'),
('Jardins Recanto das Rosas'),
('Jordanópolis'),
('José Bonifacio'),
('Jurubatuba'),
('Lagoa Grande'),
('Lajeado'),
('Lapa'),
('Lapa de Baixo'),
('Lauzane Paulista'),
('Liberdade'),
('Limão'),
('Limoeiro'),
('Loteamento City Jaragua'),
('Luz'),
('Mandaqui'),
('Maranhão'),
('Mata Fria'),
('Miami Paulista'),
('Mirandópolis'),
('Moinho Velho'),
('Moóca'),
('Morada do Sol'),
('Morro do Índio'),
('Morro dos Ingleses'),
('Morro Grande'),
('Morumbi'),
('Nossa Senhora do Ó'),
('Nova Conquista'),
('Nova Piraju'),
('Núcleo Carvalho de Araújo'),
('Núcleo do Engordador'),
('Núcleo Lageado'),
('Pacaembu'),
('Paineiras do Morumbi'),
('Palanque'),
('Parada'),
('Parada Inglesa'),
('Parada XV de Novembro'),
('Paraíso'),
('Paraíso do Morumbi'),
('Paraisópolis'),
('Parelheiros'),
('Pari'),
('Parque Alto do Rio Bonito'),
('Parque Alves de Lima'),
('Parque Amazonas'),
('Parque Amélia'),
('Parque América'),
('Parque Anhangüera'),
('Parque Anhangüera (São Domingos)'),
('Parque Anhembi'),
('Parque Arariba'),
('Parque Artur Alvim'),
('Parque Atlântico'),
('Parque Bairro Morumbi'),
('Parque Belém'),
('Parque Boa Esperança'),
('Parque Bologne'),
('Parque Boturussu'),
('Parque Brasil'),
('Parque Bristol'),
('Parque Casa de Pedra'),
('Parque Central'),
('Parque Císper'),
('Parque Claudia'),
('Parque Cocaia'),
('Parque Colonial'),
('Parque Continental'),
('Parque Cristina'),
('Parque Cruzeiro do Sul'),
('Parque Cruzeiro do Sul (Vila Formosa)'),
('Parque da Mooca'),
('Parque da Vila Prudente'),
('Parque das Árvores'),
('Parque das Cerejeiras'),
('Parque das Flores'),
('Parque das Paineiras'),
('Parque Deizy'),
('Parque do Carmo'),
('Parque do Castelo'),
('Parque do Engenho'),
('Parque do Estado'),
('Parque do Lago'),
('Parque do Morumbi'),
('Parque do Otero'),
('Parque do Terceiro Lago'),
('Parque Dom João Neri'),
('Parque Doroteia'),
('Parque dos Bancários'),
('Parque dos Príncipes'),
('Parque Edu Chaves'),
('Parque Esmeralda'),
('Parque Esperança'),
('Parque Fernanda'),
('Parque Flamengo'),
('Parque Florestal'),
('Parque Fongaro'),
('Parque Grajaú'),
('Parque Guaianazes'),
('Parque Guarani'),
('Parque Ibirapuera'),
('Parque Imperial'),
('Parque Independência'),
('Parque Industrial'),
('Parque Industrial Tomas Edson'),
('Parque Ipê'),
('Parque Itaberaba'),
('Parque Jabaquara'),
('Parque Jardim Mirassol'),
('Parque Lagoa Rica'),
('Parque Lagoinha'),
('Parque Ligia'),
('Parque Luis Mucciolo'),
('Parque Malagoli'),
('Parque Mandaqui'),
('Parque Mandi'),
('Parque Maria Alice'),
('Parque Maria Domitila'),
('Parque Maria Helena'),
('Parque Maria Luiza'),
('Parque Monteiro Soares'),
('Parque Morro Doce'),
('Parque Muciolo'),
('Parque Munhoz'),
('Parque Nações Unidas'),
('Parque Novo Grajaú'),
('Parque Novo Lar'),
('Parque Novo Mundo'),
('Parque Novo Santo Amaro'),
('Parque Paineiras'),
('Parque Paiolzinho'),
('Parque Palmas do Tremembé'),
('Parque Panamericano'),
('Parque Paulistano'),
('Parque Penha'),
('Parque Pereira'),
('Parque Peruche'),
('Parque Petrópolis'),
('Parque Planalto'),
('Parque Primavera'),
('Parque Ramos Freitas'),
('Parque Reboucas'),
('Parque Recreio'),
('Parque Regina'),
('Parque Residencial Cocaia'),
('Parque Residencial D\'Abril'),
('Parque Residencial da Lapa'),
('Parque Residencial dos Lagos'),
('Parque Residencial Julia'),
('Parque Residencial Oratorio'),
('Parque Residencial Rio Bonito'),
('Parque Rodrigues Alves'),
('Parque Sabara'),
('Parque Santa Amélia'),
('Parque Santa Bárbara'),
('Parque Santa Cecília'),
('Parque Santa Cecília (Grajaú)'),
('Parque Santa Madalena'),
('Parque Santa Rita'),
('Parque Santana'),
('Parque Santo Amaro'),
('Parque Santo Antônio'),
('Parque Santo Eduardo'),
('Parque São Domingos'),
('Parque São Joaquim'),
('Parque São Jorge'),
('Parque São José'),
('Parque São Lourenço'),
('Parque São Lucas'),
('Parque São Luís'),
('Parque São Miguel'),
('Parque São Paulo'),
('Parque São Rafael'),
('Parque Savoy City'),
('Parque Sevilha'),
('Parque Sonia'),
('Parque Taipas'),
('Parque Tamari'),
('Parque Tietê'),
('Parque Tomas Saraiva'),
('Parque Universitário Espírita'),
('Parque Veloso'),
('Parque Veredas'),
('Parque Vila Maria'),
('Parque Vila Prudente'),
('Parque Vitória'),
('Pedreira'),
('Penha de França'),
('Perdizes'),
('Perus'),
('Pinheiros'),
('Piqueri'),
('Pirajussara'),
('Piraporinha'),
('Pirituba'),
('Planalto Paulista'),
('Polvilho'),
('Ponte Pequena'),
('Ponte Rasa'),
('Praia Azul'),
('Praia da Lagoa'),
('Praia do Leblon'),
('Praia Paulistinha'),
('Praias Paulistanas'),
('Promorar Vila Maria'),
('Protendit'),
('Quarta Parada'),
('Quinta da Paineira'),
('Rancho Geraldo'),
('Raposo Tavares'),
('Real Parque'),
('Recanto Alegre'),
('Recanto Ana Maria'),
('Recanto Campo Belo'),
('Recanto das Andorinhas'),
('Recanto dos Sonhos'),
('Recanto Frei Damião'),
('Recanto Marisa'),
('Recanto Monte Alegre'),
('Recanto Paraíso'),
('Recanto Santo Antônio'),
('Recanto Verde do Sol'),
('República'),
('Residencial Morumbi'),
('Residencial Sol Nascente'),
('Residencial Taipas'),
('Residencial Vilela'),
('Retiro Morumbi'),
('Rio Bonito'),
('Rio Pequeno'),
('Riviera Paulista'),
('Rolinópolis'),
('Sacomã'),
('Santa Amélia'),
('Santa Cecília'),
('Santa Efigênia'),
('Santa Etelvina'),
('Santa Inês'),
('Santa Maria'),
('Santa Teresinha'),
('Santana'),
('Santo Amaro'),
('São Domingos'),
('São João Clímaco'),
('São Judas'),
('São Lucas'),
('São Mateus'),
('São Miguel Paulista'),
('São Salvador'),
('Sapopemba'),
('Saúde'),
('Sé'),
('Sete Praias'),
('Siciliano'),
('Sítio Areião'),
('Sítio Barrocada'),
('Sitio Boa Vista'),
('Sítio Botuquara'),
('Sítio Búfalo'),
('Sítio Canela Branca'),
('Sítio Caraguata'),
('Sítio Cocaia'),
('Sítio da Figueira'),
('Sítio do Mandaqui'),
('Sítio do Morro'),
('Sítio do Piqueri'),
('Sítio Itaberaba I'),
('Sítio Itaberaba II'),
('Sítio Laredo'),
('Sítio Matsumura'),
('Sítio Morro Grande'),
('Sítio Pinheirinho'),
('Sitio Ponderosa'),
('Sítio Represa'),
('Sitio Tapera'),
('Sítio Vale Verde'),
('Socorro'),
('Sumaré'),
('Sumarezinho'),
('Super Quadra Morumbi'),
('Taipas'),
('Tatuapé'),
('Terceira Divisão'),
('Terceira Divisão de Interlagos'),
('Tremembé'),
('Três Cruzes'),
('Tucuruvi'),
('Tuparacoera'),
('Umarizal'),
('Usina Piratininga'),
('Valo Velho'),
('Várzea da Barra Funda'),
('Várzea de Baixo'),
('Veleiros'),
('Vila ABC'),
('Vila Acre'),
('Vila Adalgisa'),
('Vila Ademar'),
('Vila Água Funda'),
('Vila Agueda'),
('Vila Aimoré'),
('Vila Alabama'),
('Vila Alba'),
('Vila Albano'),
('Vila Albertina'),
('Vila Alexandria'),
('Vila Almeida'),
('Vila Alpina'),
('Vila Alteza'),
('Vila Alzira'),
('Vila Amália (Zona Leste)'),
('Vila Amália (Zona Norte)'),
('Vila Amélia'),
('Vila América'),
('Vila Americana'),
('Vila Ana Cláudia'),
('Vila Ana Rosa'),
('Vila Anadir'),
('Vila Analia'),
('Vila Anastácio'),
('Vila Andes'),
('Vila Andrade'),
('Vila Angélica'),
('Vila Angelina'),
('Vila Anglo Brasileira'),
('Vila Anhangüera'),
('Vila Antonieta'),
('Vila Antonina'),
('Vila Antônio'),
('Vila Antônio dos Santos'),
('Vila Aparecida'),
('Vila Aparecida Ivone'),
('Vila Apoena'),
('Vila Araguaia'),
('Vila Arapuã'),
('Vila Arcádia'),
('Vila Arco Íris'),
('Vila Aricanduva'),
('Vila Arriete'),
('Vila Arruda'),
('Vila Augusto'),
('Vila Aurea'),
('Vila Aurora'),
('Vila Aurora (Zona Norte)'),
('Vila Ayrosa'),
('Vila Azevedo'),
('Vila Babilônia'),
('Vila Baby'),
('Vila Bancária'),
('Vila Bancária Munhoz'),
('Vila Bandeirantes'),
('Vila Barbosa'),
('Vila Barreto'),
('Vila Baruel'),
('Vila Basileia'),
('Vila Bauab'),
('Vila Beatriz'),
('Vila Bela'),
('Vila Bela Aliança'),
('Vila Bela do Sapopemba'),
('Vila Bela Vista (Zona Norte)'),
('Vila Bela Vista (Zona Sul)'),
('Vila Belo Horizonte'),
('Vila Bertioga'),
('Vila Bianca'),
('Vila Boaçava'),
('Vila Bom Jardim'),
('Vila Bonilha'),
('Vila Bonilha Nova'),
('Vila Borges'),
('Vila Botoni'),
('Vila Bozzini'),
('Vila Brasil'),
('Vila Brasilândia'),
('Vila Brasília (Zona Sul)'),
('Vila Brasilina'),
('Vila Brasílio Machado'),
('Vila Bruna'),
('Vila Buarque'),
('Vila Buenos Aires'),
('Vila Butantã'),
('Vila Cachoeira'),
('Vila Cachoeirinha'),
('Vila Caiçara'),
('Vila Caiúba'),
('Vila Caju'),
('Vila Califórnia'),
('Vila Califórnia(Zona Sul)'),
('Vila Calu'),
('Vila Campanela'),
('Vila Campestre'),
('Vila Campo Grande'),
('Vila Canero'),
('Vila Capela'),
('Vila Caraguatá'),
('Vila Carbone'),
('Vila Cardoso'),
('Vila Cardoso Franco'),
('Vila Carioca'),
('Vila Carlos de Campos'),
('Vila Carmem'),
('Vila Carmosina'),
('Vila Carolina'),
('Vila Carrão'),
('Vila Castelo'),
('Vila Castro'),
('Vila Catupia'),
('Vila Cavaton'),
('Vila Caxambu'),
('Vila Celeste'),
('Vila Centenário'),
('Vila Central'),
('Vila Chabilândia'),
('Vila Chalot'),
('Vila Charlote'),
('Vila Chavantes'),
('Vila Chica Luisa'),
('Vila Chuca'),
('Vila Cisper'),
('Vila Clara'),
('Vila Clarice'),
('Vila Cláudia'),
('Vila Clélia'),
('Vila Clementino'),
('Vila Cleonice'),
('Vila Comercial'),
('Vila Conceição'),
('Vila Conde do Pinhal'),
('Vila Congonhas'),
('Vila Constança'),
('Vila Continental'),
('Vila Corberi'),
('Vila Cordeiro'),
('Vila Cosmopolita'),
('Vila Costa Melo'),
('Vila Cristália'),
('Vila Cruz das Almas'),
('Vila Cruzeiro'),
('Vila Cruzeiro Novo'),
('Vila Cunha Bueno'),
('Vila Curuçá'),
('Vila da Paz'),
('Vila da Saúde'),
('Vila Dalila'),
('Vila Dalva'),
('Vila Damaceno'),
('Vila Danubio Azul'),
('Vila Darli'),
('Vila das Belezas'),
('Vila das Mercês'),
('Vila Deodoro'),
('Vila Dinorah'),
('Vila Dionisia'),
('Vila Diva (Zona Leste)'),
('Vila Diva (Zona Norte)'),
('Vila Divina Pastora'),
('Vila do Bosque'),
('Vila do Castelo'),
('Vila do Encontro'),
('Vila do Sol'),
('Vila Dom José'),
('Vila Dom Pedro I'),
('Vila Dom Pedro II'),
('Vila Domitila'),
('Vila Dona Augusta'),
('Vila Dona Meta'),
('Vila Dona Sara'),
('Vila Dorna'),
('Vila dos Andradas'),
('Vila dos Andrades'),
('Vila dos Minérios'),
('Vila dos Palmares'),
('Vila dos Remédios'),
('Vila Doutor Eiras'),
('Vila Duarte'),
('Vila Ede'),
('Vila Elba'),
('Vila Eliana'),
('Vila Elias Nigri'),
('Vila Elida'),
('Vila Eliete'),
('Vila Elisio'),
('Vila Elvira'),
('Vila Elze'),
('Vila Ema'),
('Vila Emir'),
('Vila Erna'),
('Vila Ernesto'),
('Vila Escolar'),
('Vila Esmeralda'),
('Vila Espanhola'),
('Vila Esperança'),
('Vila Ester'),
('Vila Ester (Zona Norte)'),
('Vila Euthalia'),
('Vila Fachini'),
('Vila Fanton'),
('Vila Fátima'),
('Vila Fazzeoni'),
('Vila Feliz'),
('Vila Fernandes'),
('Vila Fiat Lux'),
('Vila Fidalgo'),
('Vila Fidelis Ribeiro'),
('Vila Firmiano Pinto'),
('Vila Formosa'),
('Vila Franca'),
('Vila Franci'),
('Vila Francos'),
('Vila Friburgo'),
('Vila Frugoli'),
('Vila Fukuya'),
('Vila Gabriel'),
('Vila Gea'),
('Vila Germaine'),
('Vila Germinal'),
('Vila Gertrudes'),
('Vila Gil'),
('Vila Gilda'),
('Vila Giordano'),
('Vila Gomes'),
('Vila Gomes Cardim'),
('Vila Gouveia'),
('Vila Graciosa'),
('Vila Granada'),
('Vila Graziela'),
('Vila Guaca'),
('Vila Guacuri'),
('Vila Guaraciaba'),
('Vila Guarani(Zona Leste)'),
('Vila Guarani(Zona Sul)'),
('Vila Guedes'),
('Vila Guilherme'),
('Vila Guilhermina'),
('Vila Guiomar'),
('Vila Gumercindo'),
('Vila Gustavo'),
('Vila Hadad'),
('Vila Hamburguesa'),
('Vila Hebe'),
('Vila Helena'),
('Vila Heliópolis'),
('Vila Hermínia'),
('Vila Homero'),
('Vila Hungaresa'),
('Vila Icarai'),
('Vila Ida'),
('Vila Iguaçu'),
('Vila Império'),
('Vila Inácio'),
('Vila Inah'),
('Vila Independência'),
('Vila Independente'),
('Vila Indiana'),
('Vila Industrial'),
('Vila Inglesa'),
('Vila Invernada'),
('Vila Iolanda II'),
('Vila Iolanda(Lajeado)'),
('Vila Iório'),
('Vila Ipojuca'),
('Vila Iracema'),
('Vila Irene'),
('Vila Irmãos Arnoni'),
('Vila Isa'),
('Vila Isabel'),
('Vila Isolina Mazzei'),
('Vila Itaberaba'),
('Vila Itaim'),
('Vila Ivg'),
('Vila Ivone'),
('Vila Jaci'),
('Vila Jacuí'),
('Vila Jaguara'),
('Vila Jaguari'),
('Vila Jaraguá'),
('Vila Joaniza'),
('Vila João Batista'),
('Vila Judith'),
('Vila Julio'),
('Vila Julio Cesar'),
('Vila Jurema'),
('Vila Jussara'),
('Vila Klaunig'),
('Vila Lageado'),
('Vila Laís'),
('Vila Lar Nacional'),
('Vila Leme'),
('Vila Leonor'),
('Vila Leopoldina'),
('Vila Libanesa'),
('Vila Lisboa'),
('Vila Liviero'),
('Vila Londrina'),
('Vila Lourdes'),
('Vila Lúcia'),
('Vila Lúcia Elvira'),
('Vila Luzimar'),
('Vila Macedópolis'),
('Vila Madalena'),
('Vila Mafra'),
('Vila Malvina'),
('Vila Mangalot'),
('Vila Mara'),
('Vila Maracanã'),
('Vila Marari'),
('Vila Marcelo'),
('Vila Marconi'),
('Vila Margareth'),
('Vila Margarida'),
('Vila Maria'),
('Vila Maria Alta'),
('Vila Maria Baixa'),
('Vila Maria Eugenia'),
('Vila Maria Luisa'),
('Vila Maria Trindade'),
('Vila Maria Zélia'),
('Vila Mariana'),
('Vila Marieta'),
('Vila Marilena'),
('Vila Marina'),
('Vila Maringá'),
('Vila Mariza Mazzei'),
('Vila Marte'),
('Vila Mascote'),
('Vila Matias'),
('Vila Matilde'),
('Vila Mazzei'),
('Vila Medeiros'),
('Vila Mendes'),
('Vila Mercedes'),
('Vila Mesquita'),
('Vila Miami'),
('Vila Michelina'),
('Vila Minerva'),
('Vila Mira'),
('Vila Mirante'),
('Vila Miriam'),
('Vila Mirim'),
('Vila Missionária'),
('Vila Moderna'),
('Vila Moinho Velho'),
('Vila Monte Alegre'),
('Vila Monte Santo'),
('Vila Monumento'),
('Vila Moraes'),
('Vila Moreira'),
('Vila Morgadouro'),
('Vila Morro Grande'),
('Vila Morse'),
('Vila Morumbi'),
('Vila Nair'),
('Vila Nancy'),
('Vila Narciso'),
('Vila Nascente'),
('Vila Natal'),
('Vila Natália'),
('Vila Neila'),
('Vila Nelson'),
('Vila Nhocune'),
('Vila Nilo'),
('Vila Nilva'),
('Vila Nina'),
('Vila Nitro Operária'),
('Vila Nitro Química'),
('Vila Nivi'),
('Vila Noca'),
('Vila Nogueira'),
('Vila Norma'),
('Vila Nossa Senhora Aparecida'),
('Vila Nossa Senhora da Conceição'),
('Vila Nossa Senhora do Retiro'),
('Vila Nova'),
('Vila Nova Alba'),
('Vila Nova Cachoeirinha'),
('Vila Nova Caledônia'),
('Vila Nova Carolina'),
('Vila Nova Conceição'),
('Vila Nova Curuçá'),
('Vila Nova das Belezas'),
('Vila Nova Galvão'),
('Vila Nova Jaraguá'),
('Vila Nova Manchester'),
('Vila Nova Mazzei'),
('Vila Nova Parada'),
('Vila Nova Pauliceia'),
('Vila Nova Perus'),
('Vila Nova Pirajussara'),
('Vila Nova São Miguel'),
('Vila Nova Savoia'),
('Vila Nova Teresa'),
('Vila Nova União'),
('Vila Nova Utinga'),
('Vila Nova York'),
('Vila Odete'),
('Vila Olga'),
('Vila Olímpia'),
('Vila Olinda'),
('Vila Oratório'),
('Vila Paiva'),
('Vila Palmeiras'),
('Vila Paranaguá'),
('Vila Parque Jabaquara'),
('Vila Patrimonial'),
('Vila Paulicéia'),
('Vila Paulina'),
('Vila Paulista'),
('Vila Paulista I'),
('Vila Paulista II'),
('Vila Paulistana'),
('Vila Paulistania'),
('Vila Paulo Silas'),
('Vila Pedra Branca'),
('Vila Pedrosa'),
('Vila Pedroso'),
('Vila Penteado'),
('Vila Pereira Barreto'),
('Vila Pereira Cerca'),
('Vila Perus'),
('Vila Piauí'),
('Vila Picinin'),
('Vila Pierina'),
('Vila Piracicaba'),
('Vila Pirajussara'),
('Vila Pirituba'),
('Vila Pita'),
('Vila Plana'),
('Vila Polopoli'),
('Vila Pompéia'),
('Vila Ponte Rasa'),
('Vila Popular'),
('Vila Portugal'),
('Vila Portuguesa'),
('Vila Prado'),
('Vila Praia'),
('Vila Prel'),
('Vila Primavera'),
('Vila Primeiro de Outubro'),
('Vila Princesa Isabel'),
('Vila Progredior'),
('Vila Progresso (Zona Leste)'),
('Vila Progresso (Zona Norte)'),
('Vila Progresso (Zona Sul)'),
('Vila Prudente'),
('Vila Quarto Centenário'),
('Vila Quintana'),
('Vila Ramos'),
('Vila Rancho Alegre'),
('Vila Raquel'),
('Vila Ré'),
('Vila Regente Feijó'),
('Vila Regina'),
('Vila Reis'),
('Vila Remo'),
('Vila Renato (Zona Leste)'),
('Vila Renato (Zona Norte)'),
('Vila Represa'),
('Vila Ribeiro de Barros'),
('Vila Rica'),
('Vila Rio Branco'),
('Vila Robertina'),
('Vila Rodrigues'),
('Vila Romana'),
('Vila Romano'),
('Vila Romero'),
('Vila Roque'),
('Vila Rosa'),
('Vila Rosa Molla'),
('Vila Rosaria'),
('Vila Roschel'),
('Vila Roseira II'),
('Vila Rosina'),
('Vila Rubi'),
('Vila Rui Barbosa'),
('Vila Sabrina'),
('Vila Salete'),
('Vila Sampaio'),
('Vila Santa Catarina'),
('Vila Santa Clara'),
('Vila Santa Cruz'),
('Vila Santa Cruz (Zona Leste)'),
('Vila Santa Delfina'),
('Vila Santa Edwiges'),
('Vila Santa Eulalia'),
('Vila Santa Inês'),
('Vila Santa Isabel'),
('Vila Santa Lúcia'),
('Vila Santa Maria'),
('Vila Santa Teresa (Zona Leste)'),
('Vila Santa Teresa (Zona Sul)'),
('Vila Santa Teresinha'),
('Vila Santa Terezinha (Zona Norte)'),
('Vila Santa Virginia'),
('Vila Santana'),
('Vila Santista'),
('Vila Santo Antônio'),
('Vila Santo Estéfano'),
('Vila Santo Estevam Reis'),
('Vila Santo Estevão'),
('Vila Santo Henrique'),
('Vila Santos'),
('Vila São Camilo'),
('Vila São Domingos'),
('Vila São Francisco'),
('Vila São Geraldo'),
('Vila São José'),
('Vila São José (Cidade Dutra)'),
('Vila São José (Guaianazes)'),
('Vila São José (Ipiranga)'),
('Vila São José (Itaim Paulista)'),
('Vila São Judas'),
('Vila São Luís(Zona Oeste)'),
('Vila São Nicolau'),
('Vila São Paulo'),
('Vila São Pedro'),
('Vila São Sebastião'),
('Vila São Silvestre'),
('Vila São Silvestre (Zona Leste)'),
('Vila São Vicente'),
('Vila Sapopemba'),
('Vila Sara'),
('Vila Savoy'),
('Vila Seabra'),
('Vila Sérgio'),
('Vila Serralheiro'),
('Vila Silva Teles'),
('Vila Silveira'),
('Vila Sílvia'),
('Vila Simone'),
('Vila Sinhá'),
('Vila Siqueira (Zona Leste)'),
('Vila Siqueira (Zona Norte)'),
('Vila Sirene'),
('Vila Siria'),
('Vila Socorro'),
('Vila Sofia'),
('Vila Sol'),
('Vila Solange'),
('Vila Sônia'),
('Vila Souza'),
('Vila Stela'),
('Vila Suiça'),
('Vila Sulina'),
('Vila Suzana'),
('Vila Taiau'),
('Vila Talarico'),
('Vila Taquari'),
('Vila Teresinha'),
('Vila Tiradentes'),
('Vila Tolstoi'),
('Vila Tramontano'),
('Vila Uberabinha'),
('Vila União (Zona Leste)'),
('Vila União(Zona Norte)'),
('Vila Universitária'),
('Vila Ursulina'),
('Vila Valdemar'),
('Vila Vanda'),
('Vila Vasconcelos'),
('Vila Vera'),
('Vila Verde'),
('Vila Vermelha'),
('Vila Vessoni'),
('Vila Virginia'),
('Vila Vitório Mazzei'),
('Vila Yara'),
('Vila Zat'),
('Vila Zefira'),
('Vila Zelina'),
('Vila Zilda'),
('Vila Zulmira'),
('Vista Alegre');