CREATE TABLE IF NOT EXISTS `neighborhood` (
`ID_neighborhood` int(11) NOT NULL AUTO_INCREMENT
,`descNeighborhood` varchar(70) NOT NULL
, PRIMARY KEY (`ID_neighborhood`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `neighborhood` (`descNeighborhood`) VALUES
('Aclimacao'),
('Agua Branca'),
('Agua Fria'),
('Agua Funda'),
('Agua Rasa'),
('Alto da Boa Vista'),
('Alto da Lapa'),
('Alto da Mooca'),
('Alto da Riviera'),
('Alto de Pinheiros'),
('Alto do Pari'),
('Altos de Vila Prudente'),
('Americanopolis'),
('Anhanguera'),
('Aricanduva'),
('Artur Alvim'),
('Associacao Sobradinho'),
('Balneario Dom Carlos'),
('Balneario Mar Paulista'),
('Balneario Sao Francisco'),
('Balneario Sao Jose'),
('Baronesa'),
('Barra Funda'),
('Barragem'),
('Barro Branco (Zona Norte)'),
('Barro Branco II'),
('Bela Alianca'),
('Bela Vista'),
('Belem'),
('Belenzinho'),
('Boacava'),
('Bom Retiro'),
('Borore'),
('Bortolandia'),
('Bosque da Saude'),
('Bras'),
('Brasilandia'),
('Brooklin Novo'),
('Brooklin Paulista'),
('Burgo Paulista'),
('Butanta'),
('Cachoeirinha'),
('Cambuci'),
('Campininha'),
('Campo Belo'),
('Campo Grande'),
('Campo Limpo'),
('Campos Eliseos'),
('Cangaiba'),
('Caninde'),
('Cantareira'),
('Cantinho do Ceu'),
('Capao do Embira'),
('Capao Redondo'),
('Capela do Socorro'),
('Carandiru'),
('Carrao'),
('Casa Grande'),
('Casa Verde'),
('Casa Verde Alta'),
('Casa Verde Baixa'),
('Casa Verde Media'),
('Catumbi'),
('Caxingui'),
('Centro'),
('Cerqueira Cesar'),
('Chacara Bambu'),
('Chacara Bandeirantes'),
('Chacara Belenzinho'),
('Chacara Bosque do Sol'),
('Chacara California'),
('Chacara Cocaia'),
('Chacara Cruzeiro do Sul'),
('Chacara da Enseada'),
('Chacara das Corujas'),
('Chacara das Palmeiras'),
('Chacara do Conde'),
('Chacara do Encosto'),
('Chacara do Sol'),
('Chacara Dona Olivia'),
('Chacara Figueira Grande'),
('Chacara Flora'),
('Chacara Florida'),
('Chacara Gaivotas'),
('Chacara Inglesa'),
('Chacara Itaim'),
('Chacara Japonesa'),
('Chacara Jaragua'),
('Chacara Mafalda'),
('Chacara Maria Trindade'),
('Chacara Meyer'),
('Chacara Monte Alegre'),
('Chacara Monte Sol'),
('Chacara Morro Alto'),
('Chacara Nani'),
('Chacara Nossa Senhora Aparecida'),
('Chacara Nossa Senhora do Bom Conselho'),
('Chacara Paiva'),
('Chacara Pirajussara'),
('Chacara Pouso Alegre'),
('Chacara Santa Etelvina'),
('Chacara Santa Maria'),
('Chacara Santana'),
('Chacara Santo Amaro'),
('Chacara Santo Antonio (Zona Leste)'),
('Chacara Santo Antonio (Zona Sul)'),
('Chacara Santo Hubertus'),
('Chacara Sao Joao'),
('Chacara Sao Luis'),
('Chacara Sao Silvestre'),
('Chacara Seis de Outubro'),
('Chacara Sonho Azul'),
('Chacara Tatuape'),
('Chacara Tres Meninas'),
('Chacara Vista Alegre'),
('Chacara Vovo'),
('Chacaras Lago Grande'),
('Chapada'),
('Chora Menino'),
('Cidade Ademar'),
('Cidade Antonio Estevao de Carvalho'),
('Cidade Auxiliadora'),
('Cidade Centenario'),
('Cidade Continental'),
('Cidade D\'Abril'),
('Cidade Domitila'),
('Cidade dos Bandeirantes'),
('Cidade Dutra'),
('Cidade Fim de Semana'),
('Cidade Ipava'),
('Cidade Jardim'),
('Cidade Julia'),
('Cidade Kemel'),
('Cidade Leonor'),
('Cidade Lider'),
('Cidade Luz'),
('Cidade Mae do Ceu'),
('Cidade Moncoes'),
('Cidade Munhoz Junior'),
('Cidade Nautica'),
('Cidade Nitro Operaria'),
('Cidade Nitro Quimica'),
('Cidade Nova America'),
('Cidade Nova Heliopolis'),
('Cidade Nova Sao Miguel'),
('Cidade Patriarca'),
('Cidade Popular'),
('Cidade Sao Francisco'),
('Cidade Sao Mateus'),
('Cidade Sao Miguel'),
('Cidade Satelite'),
('Cidade Satelite Santa Barbara'),
('Cidade Tiradentes'),
('Cidade Vargas'),
('Cipo do Meio'),
('City America'),
('Clube Campestre de Sao Paulo'),
('Clube dos Funcionarios Publicos Colonia'),
('Cohab Monet'),
('Colonia (Zona Leste)'),
('Colonia (Zona Sul)'),
('Condominio Jequirituba'),
('Condominio Sao Marcos'),
('Conjunto City Jaragua'),
('Conjunto dos Bancarios'),
('Conjunto Habitacional A E Carvalho'),
('Conjunto Habitacional Aguia de Haia'),
('Conjunto Habitacional Barreira Grande'),
('Conjunto Habitacional Barro Branco I'),
('Conjunto Habitacional Barro Branco II'),
('Conjunto Habitacional Brigadeiro Eduardo Gomes'),
('Conjunto Habitacional Brigadeiro Faria Lima'),
('Conjunto Habitacional Castro Alves'),
('Conjunto Habitacional Fazenda do Carmo'),
('Conjunto Habitacional Inacio Monteiro'),
('Conjunto Habitacional Instituto Adventista'),
('Conjunto Habitacional Jardim Sao Bento'),
('Conjunto Habitacional Jardim Sao Francisco'),
('Conjunto Habitacional Jova Rural'),
('Conjunto Habitacional Juscelino Kubitschek'),
('Conjunto Habitacional Marechal Mascarenhas de Morais'),
('Conjunto Habitacional Padre Jose de Anchieta'),
('Conjunto Habitacional Padre Manoel da Nobrega'),
('Conjunto Habitacional Padre Manoel de Paiva'),
('Conjunto Habitacional Parque Valo Velho II'),
('Conjunto Habitacional Pirajussara'),
('Conjunto Habitacional Recanto dos Humildes'),
('Conjunto Habitacional Santa Etelvina I'),
('Conjunto Habitacional Santa Etelvina II'),
('Conjunto Habitacional Santa Etelvina III'),
('Conjunto Habitacional Sitio Caraguata'),
('Conjunto Habitacional Sitio Conceicao'),
('Conjunto Habitacional Teotonio Vilela'),
('Conjunto Habitacional Turistica'),
('Conjunto Habitacional Vila Nova Cachoeirinha'),
('Conjunto Promorar Estrada da Parada'),
('Conjunto Promorar Raposo Tavares'),
('Conjunto Promorar Rio Claro'),
('Conjunto Promorar Sao Luis'),
('Conjunto Promorar Sapopemba'),
('Conjunto Promorar Vila Maria III'),
('Conjunto Residencial Alpes do Jaragua'),
('Conjunto Residencial Bandeirantes'),
('Conjunto Residencial Butanta'),
('Conjunto Residencial Elisio Teixeira Leite'),
('Conjunto Residencial Ingai'),
('Conjunto Residencial Jardim Canaa'),
('Conjunto Residencial Jose Bonifacio'),
('Conjunto Residencial Morumbi'),
('Conjunto Residencial Novo Pacaembu'),
('Conjunto Residencial Paraiso'),
('Conjunto Residencial Pinheirinho'),
('Conjunto Residencial Prestes Maia'),
('Conjunto Residencial Sabara - Campo Grande'),
('Conjunto Residencial Salvador Tolezani'),
('Conjunto Residencial Santa Maria'),
('Conjunto Residencial Santa Terezinha'),
('Conjunto Residencial Sitio Oratorio'),
('Conjunto Residencial Vista Verde'),
('Consolacao'),
('Copacabana'),
('Cupece'),
('Cursino'),
('Educandario'),
('Eldorado'),
('Embu Mirim'),
('Embura'),
('Engenheiro Goulart'),
('Engenheiro Marsilac'),
('Engenheiro Trindade'),
('Ermelino Matarazzo'),
('Estancia Jaragua'),
('Estancia Mirim'),
('Estancia Tangara'),
('Favela Vila Nova Jaguare'),
('Fazenda Aricanduva'),
('Fazenda Caguacu'),
('Fazenda da Juta'),
('Fazenda Itaim'),
('Fazenda Morumbi'),
('Ferreira'),
('Flor da Cantareira'),
('Freguesia do O'),
('Furnas'),
('Gleba do Pessego'),
('Grajau'),
('Gramado'),
('Granja Julieta'),
('Granja Nossa Senhora Aparecida'),
('Guacuri'),
('Guaianazes'),
('Guaiauna'),
('Guapira'),
('Guarapiranga'),
('Guavirutuba'),
('Higienopolis'),
('Horto'),
('Horto Florestal'),
('Ibirapuera'),
('Iguatemi'),
('Imirim'),
('Indianopolis'),
('Instituto de Previdencia'),
('Interlagos'),
('Ipiranga'),
('Itaberaba'),
('Itaim'),
('Itaim Bibi'),
('Itaim Paulista'),
('Itaquera'),
('Itupu'),
('Jabaquara'),
('Jacana'),
('Jaguare'),
('Jaragua'),
('Jardim Adelaide'),
('Jardim Adelfiore'),
('Jardim Adelia'),
('Jardim Adhemar de Barros'),
('Jardim Adutora'),
('Jardim Aeroporto'),
('Jardim Aida'),
('Jardim Aimore'),
('Jardim Aladim'),
('Jardim Alfredo'),
('Jardim Almanara'),
('Jardim Almeida'),
('Jardim Almeida Prado'),
('Jardim Alpino'),
('Jardim Alteza'),
('Jardim Alto Alegre (Sao Rafael)'),
('Jardim Alto Alegre (Zona Leste)'),
('Jardim Alto do Rio Bonito'),
('Jardim Alto Paulistano'),
('Jardim Alto Pedroso'),
('Jardim Alva'),
('Jardim Alvarenga'),
('Jardim Alvina'),
('Jardim Alviverde'),
('Jardim Alvorada (Zona Norte)'),
('Jardim Alvorada (Zona Oeste)'),
('Jardim Alvorada (Zona Sul)'),
('Jardim Alzira'),
('Jardim Amalia'),
('Jardim Amaralina'),
('Jardim America'),
('Jardim America da Penha'),
('Jardim Ampliacao'),
('Jardim Ana Lucia'),
('Jardim Ana Maria'),
('Jardim Ana Rosa'),
('Jardim Analia Franco'),
('Jardim Anchieta'),
('Jardim Andarai'),
('Jardim Angela (Zona Leste)'),
('Jardim Angela (Zona Sul)'),
('Jardim Angelina'),
('Jardim Anhanguera'),
('Jardim Antartica'),
('Jardim Aparecida'),
('Jardim Apuana'),
('Jardim Apura'),
('Jardim Aracati'),
('Jardim Arantes'),
('Jardim Arco-Iris'),
('Jardim Aricanduva'),
('Jardim Aristocrata'),
('Jardim Arize'),
('Jardim Arizona'),
('Jardim Arpoador'),
('Jardim Artur Alvim'),
('Jardim Assuncao'),
('Jardim Ataliba Leonel'),
('Jardim Atibaia'),
('Jardim Atlantico'),
('Jardim Augusta'),
('Jardim Augusto'),
('Jardim Aurea'),
('Jardim Aurelia'),
('Jardim Aurelio'),
('Jardim Aurora (Zona Leste)'),
('Jardim Aurora (Zona Oeste)'),
('Jardim Avelino'),
('Jardim Avenida'),
('Jardim Azano I'),
('Jardim Azano II'),
('Jardim Bandeirante'),
('Jardim Bandeirante (Sao Rafael)'),
('Jardim Bandeirantes'),
('Jardim Bandeirantes (Zona Norte)'),
('Jardim Barbara'),
('Jardim Barros'),
('Jardim Bartira'),
('Jardim Batalha'),
('Jardim Beatriz'),
('Jardim Beatriz (Zona Leste)'),
('Jardim Bela Vista (Zona Norte)'),
('Jardim Bela Vista (Zona Sul)'),
('Jardim Belaura'),
('Jardim Belcito'),
('Jardim Belem'),
('Jardim Belgica'),
('Jardim Benfica'),
('Jardim Bibi'),
('Jardim Bichinhos'),
('Jardim Boa Esperanca'),
('Jardim Boa Sorte'),
('Jardim Boa Vista (Zona Oeste)'),
('Jardim Boa Vista (Zona Sul)'),
('Jardim Bom Clima'),
('Jardim Bom Pastor'),
('Jardim Bom Refugio'),
('Jardim Bonfiglioli'),
('Jardim Bonito'),
('Jardim Borba Gato'),
('Jardim Bosque do Sol'),
('Jardim Botucatu'),
('Jardim Brasil (Zona Norte)'),
('Jardim Brasil (Zona Sul)'),
('Jardim Brasil Novo'),
('Jardim Brasilia'),
('Jardim Brasilia (Zona Leste)'),
('Jardim Brasilia (Zona Norte)'),
('Jardim Britania'),
('Jardim Bronzato'),
('Jardim Buriti'),
('Jardim Cabore'),
('Jardim Cabucu'),
('Jardim Cachoeira'),
('Jardim Caguassu'),
('Jardim Camara'),
('Jardim Camargo Novo'),
('Jardim Cambara'),
('Jardim Campinas'),
('Jardim Campo dos Ferreiros'),
('Jardim Campo Grande'),
('Jardim Campo Limpo'),
('Jardim Campo Limpo (Zona Norte)'),
('Jardim Campos'),
('Jardim Capao Redondo'),
('Jardim Capela'),
('Jardim Capelinha'),
('Jardim Caravelas'),
('Jardim Carlu'),
('Jardim Carolina'),
('Jardim Carombe'),
('Jardim Casa Grande'),
('Jardim Casa Pintada'),
('Jardim Casablanca'),
('Jardim Castelo'),
('Jardim Castro Alves'),
('Jardim Catanduva'),
('Jardim Catarina'),
('Jardim Cecy'),
('Jardim Cedro do Libano'),
('Jardim Celeste'),
('Jardim Celia'),
('Jardim Centenario'),
('Jardim Central'),
('Jardim Cercado da Estrada'),
('Jardim Chester'),
('Jardim Cibele'),
('Jardim Cidade Pirituba'),
('Jardim Cidalia'),
('Jardim Cimobil'),
('Jardim Cinco de Julho'),
('Jardim Clara Regina'),
('Jardim Clarice'),
('Jardim Claudia'),
('Jardim Cleide'),
('Jardim Clelia'),
('Jardim Climax'),
('Jardim Cliper'),
('Jardim Coimbra'),
('Jardim Colina'),
('Jardim Colombo'),
('Jardim Colonial'),
('Jardim Colorado'),
('Jardim Comercial'),
('Jardim Concordia'),
('Jardim Consorcio'),
('Jardim Consupler'),
('Jardim Copacabana'),
('Jardim Cordeiro'),
('Jardim Corisco'),
('Jardim Cotching'),
('Jardim Cotiana'),
('Jardim Cotinha'),
('Jardim Cristal'),
('Jardim Cristalia'),
('Jardim Cristina'),
('Jardim Cruzeiro'),
('Jardim Cupece'),
('Jardim D\'Abril'),
('Jardim da Cachoeira'),
('Jardim da Campina'),
('Jardim da Conquista (Zona Leste)'),
('Jardim da Conquista (Zona Oeste)'),
('Jardim da Gloria'),
('Jardim da Laranjeira (Zona Leste)'),
('Jardim da Pedreira'),
('Jardim da Saude'),
('Jardim Dalmo'),
('Jardim Damasceno'),
('Jardim Danfer'),
('Jardim Danubio Azul'),
('Jardim das Acacias'),
('Jardim das Bandeiras'),
('Jardim das Camelias'),
('Jardim das Camelias (Zona Sul)'),
('Jardim das Esmeraldas'),
('Jardim das Flores'),
('Jardim das Fontes'),
('Jardim das Gracas'),
('Jardim das Imbuias'),
('Jardim das Laranjeiras'),
('Jardim das Laranjeiras (Zona Sul)'),
('Jardim das Oliveiras'),
('Jardim das Oliveiras (Zona Sul)'),
('Jardim das Palmas'),
('Jardim das Palmeiras'),
('Jardim das Palmeiras (Zona Sul)'),
('Jardim das Pedras'),
('Jardim das Pedras(Zona Sul)'),
('Jardim das Praias'),
('Jardim das Rosas (Iguatemi)'),
('Jardim das Rosas (Zona Leste I)'),
('Jardim das Rosas (Zona Norte)'),
('Jardim das Rosas (Zona Sul)'),
('Jardim das Vertentes'),
('Jardim Daysy'),
('Jardim de Lorenzo'),
('Jardim Denise'),
('Jardim Denyse'),
('Jardim Deolinda'),
('Jardim Dinar'),
('Jardim Dinorah'),
('Jardim Diomar'),
('Jardim Dionisio'),
('Jardim do Alto'),
('Jardim do Campo'),
('Jardim do Carmo'),
('Jardim do Centro'),
('Jardim do Colegio'),
('Jardim do Colegio (Zona Norte)'),
('Jardim do Divino'),
('Jardim do Lago'),
('Jardim do Russo'),
('Jardim do Sol'),
('Jardim do Tiro'),
('Jardim Dom Bosco'),
('Jardim Dom Fernando'),
('Jardim Dom Jose'),
('Jardim Domitila'),
('Jardim Dona Deolinda'),
('Jardim Dona Sinha'),
('Jardim Donaria'),
('Jardim dos Alamos'),
('Jardim dos Bichinhos'),
('Jardim dos Cataldis'),
('Jardim dos Estados'),
('Jardim dos Eucaliptos'),
('Jardim dos Francos'),
('Jardim dos Ipes'),
('Jardim dos Jacarandas'),
('Jardim dos Lagos'),
('Jardim dos Manacas'),
('Jardim dos Pereiras'),
('Jardim dos Pinheiros'),
('Jardim dos Prados'),
('Jardim Dracena'),
('Jardim Drumond'),
('Jardim Duprat'),
('Jardim Edda'),
('Jardim Edi'),
('Jardim Edilene'),
('Jardim Edith'),
('Jardim Edwiges'),
('Jardim Egle'),
('Jardim Elba'),
('Jardim Eledy'),
('Jardim Eliana'),
('Jardim Eliane'),
('Jardim Elisa Maria'),
('Jardim Elisio'),
('Jardim Eliza'),
('Jardim Elizabeth'),
('Jardim Ellus'),
('Jardim Elza'),
('Jardim Emilia'),
('Jardim Engenheiro Visconti'),
('Jardim Ernestina'),
('Jardim Esmeralda'),
('Jardim Esmeralda (Zona Sul)'),
('Jardim Esperanca'),
('Jardim Ester'),
('Jardim Ester Yolanda'),
('Jardim Estrela'),
('Jardim Estrela D\'alva'),
('Jardim Etelvina'),
('Jardim Europa'),
('Jardim Eva'),
('Jardim Everest'),
('Jardim Fanganiello'),
('Jardim Faria Lima'),
('Jardim Felicidade (Zona Norte)'),
('Jardim Felicidade (Zona Oeste)'),
('Jardim Fernandes'),
('Jardim Figueira Grande'),
('Jardim Filhos da Terra'),
('Jardim Fim de Semana'),
('Jardim Flamingo'),
('Jardim Flor de Maio'),
('Jardim Floresta'),
('Jardim Florida Paulista'),
('Jardim Fluminense'),
('Jardim Fontalis'),
('Jardim Fonte do Morumbi'),
('Jardim Fonte Sao Miguel'),
('Jardim Franca'),
('Jardim Francisco Mendes'),
('Jardim Francisco Mentem'),
('Jardim Franganielo'),
('Jardim Fraternidade'),
('Jardim Fujihara'),
('Jardim Galli'),
('Jardim Germania'),
('Jardim Gianetti'),
('Jardim Gilberto'),
('Jardim Gilda Maria'),
('Jardim Gloria'),
('Jardim Gonzaga'),
('Jardim Grimaldi'),
('Jardim Guacuri'),
('Jardim Guaianazes'),
('Jardim Guairaca'),
('Jardim Guanabara'),
('Jardim Guanca'),
('Jardim Guanhembu'),
('Jardim Guapira'),
('Jardim Guarani'),
('Jardim Guarapiranga'),
('Jardim Guarau'),
('Jardim Guaruja'),
('Jardim Guedala'),
('Jardim Guiomar'),
('Jardim Gustavo'),
('Jardim Hadad'),
('Jardim Haia do Carrao'),
('Jardim Harmonia'),
('Jardim Hebrom'),
('Jardim Helena'),
('Jardim Helga'),
('Jardim Heliomar'),
('Jardim Heloisa'),
('Jardim Hercilia'),
('Jardim Herculano'),
('Jardim Herplin'),
('Jardim Hipico'),
('Jardim Horizonte Azul'),
('Jardim Horto Florestal'),
('Jardim Humaita'),
('Jardim Humberto Nastari'),
('Jardim Iae'),
('Jardim Iara'),
('Jardim Ibirapuera'),
('Jardim Ibiratiba'),
('Jardim Ibitirama'),
('Jardim Icara'),
('Jardim Icarai'),
('Jardim Ida Guedes'),
('Jardim Ideal'),
('Jardim Iguatemi'),
('Jardim Imbe'),
('Jardim Imperador (Zona Leste)'),
('Jardim Imperador (Zona Sul)'),
('Jardim Imperial'),
('Jardim Imperio'),
('Jardim Indaia'),
('Jardim Independencia'),
('Jardim Inga'),
('Jardim Internacional'),
('Jardim Ipanema (Cidade Lider)'),
('Jardim Ipanema (Sao Miguel)'),
('Jardim Ipanema (Zona Oeste)'),
('Jardim Ipanema (Zona Sul)'),
('Jardim Ipe'),
('Jardim Ipora'),
('Jardim Iporanga'),
('Jardim Iracema'),
('Jardim Irapiranga'),
('Jardim Irene'),
('Jardim Iris'),
('Jardim Itacolomi'),
('Jardim Itajai'),
('Jardim Italia'),
('Jardim Itamaraty'),
('Jardim Itaoca'),
('Jardim Itapema'),
('Jardim Itapemirim'),
('Jardim Itapeva'),
('Jardim Itapolis'),
('Jardim Itapura'),
('Jardim Itatiaia'),
('Jardim Itatinga'),
('Jardim Iva'),
('Jardim Ivana'),
('Jardim Ivete'),
('Jardim Ivone'),
('Jardim Jabaquara'),
('Jardim Jacana'),
('Jardim Jamaica'),
('Jardim Japao'),
('Jardim Jaqueline'),
('Jardim Jaragua'),
('Jardim Jaragua (Itaim Paulista)'),
('Jardim Jaragua (Sao Domingos)'),
('Jardim Jau (Zona Leste)'),
('Jardim Jau (Zona Sul)'),
('Jardim Jeriva'),
('Jardim Joamar'),
('Jardim Joana D\'Arc'),
('Jardim Joao XXIII'),
('Jardim Jordao'),
('Jardim Jua'),
('Jardim Julieta'),
('Jardim Jurema'),
('Jardim Jussara'),
('Jardim Kagohara'),
('Jardim Kaj'),
('Jardim Keralux'),
('Jardim Kika'),
('Jardim Kioto'),
('Jardim Labitary'),
('Jardim Lajeado'),
('Jardim Lallo'),
('Jardim Laone'),
('Jardim Lapena'),
('Jardim Lar Sao Paulo'),
('Jardim Laranjal'),
('Jardim Laranjeiras'),
('Jardim Laura'),
('Jardim Leila'),
('Jardim Leme'),
('Jardim Leni'),
('Jardim Leonardo'),
('Jardim Leonidas Moreira'),
('Jardim Leonor'),
('Jardim Leonor Mendes de Barros'),
('Jardim Leticia'),
('Jardim Libano'),
('Jardim Lice'),
('Jardim Lider'),
('Jardim Lideranca'),
('Jardim Lidia'),
('Jardim Lilah'),
('Jardim Limoeiro'),
('Jardim Lisboa'),
('Jardim Londrina'),
('Jardim Los Angeles'),
('Jardim Lourdes'),
('Jardim Lourdes (Zona Sul)'),
('Jardim Luanda'),
('Jardim Lucelia'),
('Jardim Lucia'),
('Jardim Luciana'),
('Jardim Lucinda'),
('Jardim Lucio de Castro'),
('Jardim Lugo'),
('Jardim Luisa'),
('Jardim Luso'),
('Jardim Luzitania'),
('Jardim Mabel'),
('Jardim Macedonia'),
('Jardim Machado'),
('Jardim Maggi'),
('Jardim Maia'),
('Jardim Malia I'),
('Jardim Malia II'),
('Jardim Mangalot'),
('Jardim Mar Lune'),
('Jardim Maraba'),
('Jardim Maraba(Zona Sul)'),
('Jardim Maraca'),
('Jardim Maracana'),
('Jardim Marajoara'),
('Jardim Marcel'),
('Jardim Marcelo'),
('Jardim Marciano'),
('Jardim Marco Paulo'),
('Jardim Margarida'),
('Jardim Maria Amalia'),
('Jardim Maria Augusta'),
('Jardim Maria Duarte'),
('Jardim Maria Emilia'),
('Jardim Maria Estela'),
('Jardim Maria Fernandes'),
('Jardim Maria Lidia'),
('Jardim Maria Lucia'),
('Jardim Maria Luiza'),
('Jardim Maria Margarida'),
('Jardim Maria Nazare'),
('Jardim Maria Rita'),
('Jardim Maria Sampaio'),
('Jardim Maria Virginia'),
('Jardim Mariane'),
('Jardim Marilda'),
('Jardim Marilia'),
('Jardim Mariliza'),
('Jardim Marilu'),
('Jardim Marina'),
('Jardim Maringa'),
('Jardim Marisa'),
('Jardim Maristela'),
('Jardim Marpu'),
('Jardim Marquesa'),
('Jardim Martha'),
('Jardim Martini'),
('Jardim Martinica'),
('Jardim Martins Silva'),
('Jardim Mascarenhas'),
('Jardim Matarazzo'),
('Jardim Mazza'),
('Jardim Meliunas'),
('Jardim Melo'),
('Jardim Mikail'),
('Jardim Mimar'),
('Jardim Miragaia'),
('Jardim Mirante'),
('Jardim Miriam'),
('Jardim Mitsutani'),
('Jardim Modelo'),
('Jardim Monica'),
('Jardim Monjolo'),
('Jardim Monte Alegre'),
('Jardim Monte Alegre (Zona Norte)'),
('Jardim Monte Azul'),
('Jardim Monte Belo'),
('Jardim Monte Belo (Raposo Tavares)'),
('Jardim Monte Kemel'),
('Jardim Monte Verde'),
('Jardim Morais Prado'),
('Jardim Moreno'),
('Jardim Morganti'),
('Jardim Morro Verde'),
('Jardim Morumbi'),
('Jardim Mutinga'),
('Jardim Myrna'),
('Jardim Myrna II'),
('Jardim Nadir'),
('Jardim Nagib Salem'),
('Jardim Nair'),
('Jardim Nakamura'),
('Jardim Namba'),
('Jardim Nardini'),
('Jardim Nastari'),
('Jardim Natal'),
('Jardim Naufal'),
('Jardim Nazareth'),
('Jardim Neide'),
('Jardim Neila'),
('Jardim Nelia'),
('Jardim Nelia IV'),
('Jardim Nelly'),
('Jardim Nice'),
('Jardim Niteroi'),
('Jardim Nizia'),
('Jardim Noemia'),
('Jardim Nordeste'),
('Jardim Norma'),
('Jardim Noronha'),
('Jardim Nossa Senhora Aparecida'),
('Jardim Nossa Senhora do Carmo'),
('Jardim Nosso Lar'),
('Jardim Nova Brasilia'),
('Jardim Nova Colonia'),
('Jardim Nova Germania'),
('Jardim Nova Guaianazes'),
('Jardim Nova Harmonia'),
('Jardim Nova Tereza'),
('Jardim Nova Vitoria I'),
('Jardim Nova Vitoria II'),
('Jardim Nove de Julho'),
('Jardim Novo Carrao'),
('Jardim Novo Horizonte'),
('Jardim Novo Jau'),
('Jardim Novo Lar'),
('Jardim Novo Mundo'),
('Jardim Novo Parelheiros'),
('Jardim Novo Santo Amaro'),
('Jardim Novo Taboao'),
('Jardim Odete'),
('Jardim Olinda'),
('Jardim Olympia'),
('Jardim Ondina'),
('Jardim Orbam'),
('Jardim Oriental'),
('Jardim Oriental (Parelheiros)'),
('Jardim Orion'),
('Jardim Orly'),
('Jardim Ormendina'),
('Jardim Outono'),
('Jardim Palmares (Zona Norte)'),
('Jardim Palmares (Zona Sul)'),
('Jardim Panorama'),
('Jardim Panorama (Zona Leste)'),
('Jardim Panorama (Zona Sul)'),
('Jardim Panorama D\'Oeste'),
('Jardim Pantanal'),
('Jardim Papai Noel'),
('Jardim Paqueta (Zona Norte)'),
('Jardim Paqueta (Zona Sul)'),
('Jardim Para'),
('Jardim Paraguacu'),
('Jardim Paraiso'),
('Jardim Paris'),
('Jardim Parque Morumbi'),
('Jardim Patente'),
('Jardim Patente Novo'),
('Jardim Pauliceia'),
('Jardim Paulista'),
('Jardim Paulistano'),
('Jardim Paulistano (Zona Norte)'),
('Jardim Paulo Afonso'),
('Jardim Paulo Borba'),
('Jardim Paulo VI'),
('Jardim Pedra Branca'),
('Jardim Pedra Branca II'),
('Jardim Pedro Jose Nunes'),
('Jardim Penha'),
('Jardim Pereira Leite'),
('Jardim Peri'),
('Jardim Peri Novo'),
('Jardim Peri Peri'),
('Jardim Perola I'),
('Jardim Perola II'),
('Jardim Perola III'),
('Jardim Perus'),
('Jardim Petisco'),
('Jardim Petropolis'),
('Jardim Picolo'),
('Jardim Pinheiros'),
('Jardim Piqueri'),
('Jardim Piqueroby'),
('Jardim Piracema'),
('Jardim Piracuama'),
('Jardim Pirajussara'),
('Jardim Piratininga'),
('Jardim Pirituba'),
('Jardim Planalto'),
('Jardim Poleti'),
('Jardim Pongilutti'),
('Jardim Ponte Rasa'),
('Jardim Popular'),
('Jardim Portal I e II'),
('Jardim Porteira Grande'),
('Jardim Pouso Alegre'),
('Jardim Prainha'),
('Jardim Presidente'),
('Jardim Previdencia'),
('Jardim Primavera'),
('Jardim Princesa'),
('Jardim Progresso'),
('Jardim Promissao'),
('Jardim Prudencia'),
('Jardim Quarto Centenario'),
('Jardim Quisisana (Vila Nova Curuca)'),
('Jardim Ramala'),
('Jardim Raposo Tavares'),
('Jardim Real'),
('Jardim Recanto do Sol'),
('Jardim Recanto Verde'),
('Jardim Record'),
('Jardim Recreio'),
('Jardim Redencao'),
('Jardim Redil'),
('Jardim Regina'),
('Jardim Regis'),
('Jardim Reimberg'),
('Jardim Remo'),
('Jardim Represa'),
('Jardim Represa (Parelheiros)'),
('Jardim Republica'),
('Jardim Ricardo'),
('Jardim Rincao'),
('Jardim Rio Bonito'),
('Jardim Rio Douro'),
('Jardim Rio Pequeno'),
('Jardim Riviera'),
('Jardim Rizzo'),
('Jardim Robru'),
('Jardim Rodolfo Pirani'),
('Jardim Romano'),
('Jardim Roni'),
('Jardim Rosa Maria'),
('Jardim Rosalina'),
('Jardim Rosana'),
('Jardim Roschel'),
('Jardim Roseli'),
('Jardim Rosider'),
('Jardim Rosina'),
('Jardim Rosinha'),
('Jardim Rossin'),
('Jardim Rubilene'),
('Jardim Rubio'),
('Jardim Russo'),
('Jardim Ruth'),
('Jardim S Kemel'),
('Jardim Sabara'),
('Jardim Sabia'),
('Jardim Sabia II'),
('Jardim Sagrado Coracao'),
('Jardim Samambaia'),
('Jardim Samara'),
('Jardim Samas'),
('Jardim Sandra'),
('Jardim Sandra Maria'),
('Jardim Santa Adelia'),
('Jardim Santa Barbara'),
('Jardim Santa Branca'),
('Jardim Santa Cecilia'),
('Jardim Santa Cruz (Campo Grande)'),
('Jardim Santa Cruz (Parelheiros)'),
('Jardim Santa Cruz (Sacoma)'),
('Jardim Santa Cruz (Zona Norte)'),
('Jardim Santa Edwiges (Capela do Socorro)'),
('Jardim Santa Edwiges (Grajau)'),
('Jardim Santa Efigenia'),
('Jardim Santa Emilia'),
('Jardim Santa Etelvina'),
('Jardim Santa Fe (Zona Oeste)'),
('Jardim Santa Fe (Zona Sul)'),
('Jardim Santa Filomena'),
('Jardim Santa Francisca Cabrini'),
('Jardim Santa Gertrudes'),
('Jardim Santa Helena'),
('Jardim Santa Ines'),
('Jardim Santa Josefina'),
('Jardim Santa Lucrecia'),
('Jardim Santa Luisa'),
('Jardim Santa Marcelina'),
('Jardim Santa Margarida'),
('Jardim Santa Maria'),
('Jardim Santa Monica'),
('Jardim Santa Rita'),
('Jardim Santa Tereza'),
('Jardim Santa Terezinha'),
('Jardim Santa Terezinha (Parelheiros)'),
('Jardim Santa Terezinha (Pedreira)'),
('Jardim Santa Terezinha (Zona Leste)'),
('Jardim Santa Zelia'),
('Jardim Santana'),
('Jardim Santo Alberto'),
('Jardim Santo Amaro'),
('Jardim Santo Andre'),
('Jardim Santo Antoninho'),
('Jardim Santo Antonio'),
('Jardim Santo Elias'),
('Jardim Santo Elias (Sao Miguel)'),
('Jardim Santo Onofre'),
('Jardim Santos Dumont'),
('Jardim Sao Benedito'),
('Jardim Sao Bento'),
('Jardim Sao Bento Novo'),
('Jardim Sao Bernardo'),
('Jardim Sao Carlos (Zona Leste)'),
('Jardim Sao Carlos (Zona Sul)'),
('Jardim Sao Cristovao'),
('Jardim Sao Domingos'),
('Jardim Sao Francisco'),
('Jardim Sao Francisco (Parelheiros)'),
('Jardim Sao Francisco (Zona Leste)'),
('Jardim Sao Francisco de Assis'),
('Jardim Sao Francisco(Zona Sul)'),
('Jardim Sao Gabriel'),
('Jardim Sao Gilberto'),
('Jardim Sao Goncalo'),
('Jardim Sao Januario'),
('Jardim Sao Joao'),
('Jardim Sao Joao (Guaianazes)'),
('Jardim Sao Joao (Jaragua)'),
('Jardim Sao Joao (Sao Rafael)'),
('Jardim Sao Joao (Zona Leste)'),
('Jardim Sao Joao (Zona Norte)'),
('Jardim Sao Joaquim'),
('Jardim Sao Jorge'),
('Jardim Sao Jose'),
('Jardim Sao Jose (Artur Alvim)'),
('Jardim Sao Jose (Sao Mateus)'),
('Jardim Sao Jose (Zona Norte)'),
('Jardim Sao Jose (Zona Sul)'),
('Jardim Sao Judas Tadeu'),
('Jardim Sao Lourenco'),
('Jardim Sao Luis'),
('Jardim Sao Luis (Zona Leste)'),
('Jardim Sao Luis (Zona Norte)'),
('Jardim Sao Manoel'),
('Jardim Sao Martinho'),
('Jardim Sao Mateus'),
('Jardim Sao Miguel'),
('Jardim Sao Nicolau'),
('Jardim Sao Norberto'),
('Jardim Sao Paulo(Zona Leste)'),
('Jardim Sao Paulo(Zona Norte)'),
('Jardim Sao Pedro'),
('Jardim Sao Pedro (Zona Sul)'),
('Jardim Sao Rafael'),
('Jardim Sao Raimundo'),
('Jardim Sao Remo'),
('Jardim Sao Ricardo'),
('Jardim Sao Roberto'),
('Jardim Sao Roque'),
('Jardim Sao Saverio'),
('Jardim Sao Sebastiao'),
('Jardim Sao Silvestre'),
('Jardim Sao Vicente'),
('Jardim Sao Vitor'),
('Jardim Sapopemba'),
('Jardim Sarah'),
('Jardim Satelite'),
('Jardim Saude'),
('Jardim Scaff'),
('Jardim Seckler'),
('Jardim Selma'),
('Jardim Senice'),
('Jardim Sertaozinho'),
('Jardim Sete de Setembro'),
('Jardim Shangrila (Zona Norte)'),
('Jardim Shangrila (Zona Sul)'),
('Jardim Silva Teles'),
('Jardim Silveira'),
('Jardim Silvia (Zona Leste)'),
('Jardim Silvia (Zona Oeste)'),
('Jardim Sipramar'),
('Jardim Soares'),
('Jardim Solange'),
('Jardim Somara'),
('Jardim Sonia (Zona Sul)'),
('Jardim Sonia Inga'),
('Jardim Sonia Marly'),
('Jardim Sonia Regina'),
('Jardim Soraia'),
('Jardim Souza'),
('Jardim Sul Sao Paulo'),
('Jardim Suzana'),
('Jardim Sydney'),
('Jardim Taboao'),
('Jardim Taipas'),
('Jardim Tamoio'),
('Jardim Tanay'),
('Jardim Tango'),
('Jardim Tapera'),
('Jardim Taquaral'),
('Jardim Teixeira'),
('Jardim Tenani'),
('Jardim Teresa'),
('Jardim Teresa Cristina'),
('Jardim Textil'),
('Jardim Thealia'),
('Jardim Thomaz'),
('Jardim Tiete'),
('Jardim Tiro ao Pombo'),
('Jardim Toca'),
('Jardim Tremembe'),
('Jardim Tres Coracoes'),
('Jardim Tres Marias'),
('Jardim Triana'),
('Jardim Tricolor'),
('Jardim Tropical'),
('Jardim Trussardi'),
('Jardim Tua'),
('Jardim Tupa'),
('Jardim Tupi'),
('Jardim Turquesa'),
('Jardim Uberaba'),
('Jardim Ubirajara (Zona Leste)'),
('Jardim Ubirajara (Zona Sul)'),
('Jardim Uirapuru'),
('Jardim Umarizal'),
('Jardim Umuarama'),
('Jardim Uniao'),
('Jardim Uniserve'),
('Jardim Universal'),
('Jardim Universidade Pinheiros'),
('Jardim Universitario'),
('Jardim Vale das Virtudes'),
('Jardim Vale do Ribeira'),
('Jardim Vale do Sol'),
('Jardim Valparaiso'),
('Jardim Valquiria'),
('Jardim Varginha'),
('Jardim Vaz de Lima'),
('Jardim Vazani'),
('Jardim Vera Cruz'),
('Jardim Vera Cruz (Parelheiros)'),
('Jardim Vera Cruz(Zona Leste)'),
('Jardim Vera Cruz(Zona Sul)'),
('Jardim Vergueiro'),
('Jardim Vergueiro (Sacoma)'),
('Jardim Veronia'),
('Jardim Viana'),
('Jardim Vieira'),
('Jardim Vila Carrao'),
('Jardim Vila Formosa'),
('Jardim Vila Mariana'),
('Jardim Vila Nova Progresso'),
('Jardim Vila Rica'),
('Jardim Vilas Boas'),
('Jardim Vilma'),
('Jardim Virginia'),
('Jardim Virginia Bianca'),
('Jardim Vista Alegre'),
('Jardim Vista Linda'),
('Jardim Vitoria'),
('Jardim Vitoria Regia'),
('Jardim Vitoria Regia (Zona Norte)'),
('Jardim Vivan'),
('Jardim Wanda'),
('Jardim Wilma Flor'),
('Jardim Yara'),
('Jardim Ymay'),
('Jardim Zaira'),
('Jardim Zelia'),
('Jardim Zilda'),
('Jardins'),
('Jardins Recanto das Rosas'),
('Jordanopolis'),
('Jose Bonifacio'),
('Jurubatuba'),
('Lagoa Grande'),
('Lajeado'),
('Lapa'),
('Lapa de Baixo'),
('Lauzane Paulista'),
('Liberdade'),
('Limao'),
('Limoeiro'),
('Loteamento City Jaragua'),
('Luz'),
('Mandaqui'),
('Maranhao'),
('Mata Fria'),
('Miami Paulista'),
('Mirandopolis'),
('Moinho Velho'),
('Mooca'),
('Morada do Sol'),
('Morro do Indio'),
('Morro dos Ingleses'),
('Morro Grande'),
('Morumbi'),
('Nossa Senhora do O'),
('Nova Conquista'),
('Nova Piraju'),
('Nucleo Carvalho de Araujo'),
('Nucleo do Engordador'),
('Nucleo Lageado'),
('Pacaembu'),
('Paineiras do Morumbi'),
('Palanque'),
('Parada'),
('Parada Inglesa'),
('Parada XV de Novembro'),
('Paraiso'),
('Paraiso do Morumbi'),
('Paraisopolis'),
('Parelheiros'),
('Pari'),
('Parque Alto do Rio Bonito'),
('Parque Alves de Lima'),
('Parque Amazonas'),
('Parque Amelia'),
('Parque America'),
('Parque Anhanguera'),
('Parque Anhanguera (Sao Domingos)'),
('Parque Anhembi'),
('Parque Arariba'),
('Parque Artur Alvim'),
('Parque Atlantico'),
('Parque Bairro Morumbi'),
('Parque Belem'),
('Parque Boa Esperanca'),
('Parque Bologne'),
('Parque Boturussu'),
('Parque Brasil'),
('Parque Bristol'),
('Parque Casa de Pedra'),
('Parque Central'),
('Parque Cisper'),
('Parque Claudia'),
('Parque Cocaia'),
('Parque Colonial'),
('Parque Continental'),
('Parque Cristina'),
('Parque Cruzeiro do Sul'),
('Parque Cruzeiro do Sul (Vila Formosa)'),
('Parque da Mooca'),
('Parque da Vila Prudente'),
('Parque das Arvores'),
('Parque das Cerejeiras'),
('Parque das Flores'),
('Parque das Paineiras'),
('Parque Deizy'),
('Parque do Carmo'),
('Parque do Castelo'),
('Parque do Engenho'),
('Parque do Estado'),
('Parque do Lago'),
('Parque do Morumbi'),
('Parque do Otero'),
('Parque do Terceiro Lago'),
('Parque Dom Joao Neri'),
('Parque Doroteia'),
('Parque dos Bancarios'),
('Parque dos Principes'),
('Parque Edu Chaves'),
('Parque Esmeralda'),
('Parque Esperanca'),
('Parque Fernanda'),
('Parque Flamengo'),
('Parque Florestal'),
('Parque Fongaro'),
('Parque Grajau'),
('Parque Guaianazes'),
('Parque Guarani'),
('Parque Ibirapuera'),
('Parque Imperial'),
('Parque Independencia'),
('Parque Industrial'),
('Parque Industrial Tomas Edson'),
('Parque Ipe'),
('Parque Itaberaba'),
('Parque Jabaquara'),
('Parque Jardim Mirassol'),
('Parque Lagoa Rica'),
('Parque Lagoinha'),
('Parque Ligia'),
('Parque Luis Mucciolo'),
('Parque Malagoli'),
('Parque Mandaqui'),
('Parque Mandi'),
('Parque Maria Alice'),
('Parque Maria Domitila'),
('Parque Maria Helena'),
('Parque Maria Luiza'),
('Parque Monteiro Soares'),
('Parque Morro Doce'),
('Parque Muciolo'),
('Parque Munhoz'),
('Parque Nacoes Unidas'),
('Parque Novo Grajau'),
('Parque Novo Lar'),
('Parque Novo Mundo'),
('Parque Novo Santo Amaro'),
('Parque Paineiras'),
('Parque Paiolzinho'),
('Parque Palmas do Tremembe'),
('Parque Panamericano'),
('Parque Paulistano'),
('Parque Penha'),
('Parque Pereira'),
('Parque Peruche'),
('Parque Petropolis'),
('Parque Planalto'),
('Parque Primavera'),
('Parque Ramos Freitas'),
('Parque Reboucas'),
('Parque Recreio'),
('Parque Regina'),
('Parque Residencial Cocaia'),
('Parque Residencial D\'Abril'),
('Parque Residencial da Lapa'),
('Parque Residencial dos Lagos'),
('Parque Residencial Julia'),
('Parque Residencial Oratorio'),
('Parque Residencial Rio Bonito'),
('Parque Rodrigues Alves'),
('Parque Sabara'),
('Parque Santa Amelia'),
('Parque Santa Barbara'),
('Parque Santa Cecilia'),
('Parque Santa Cecilia (Grajau)'),
('Parque Santa Madalena'),
('Parque Santa Rita'),
('Parque Santana'),
('Parque Santo Amaro'),
('Parque Santo Antonio'),
('Parque Santo Eduardo'),
('Parque Sao Domingos'),
('Parque Sao Joaquim'),
('Parque Sao Jorge'),
('Parque Sao Jose'),
('Parque Sao Lourenco'),
('Parque Sao Lucas'),
('Parque Sao Luis'),
('Parque Sao Miguel'),
('Parque Sao Paulo'),
('Parque Sao Rafael'),
('Parque Savoy City'),
('Parque Sevilha'),
('Parque Sonia'),
('Parque Taipas'),
('Parque Tamari'),
('Parque Tiete'),
('Parque Tomas Saraiva'),
('Parque Universitario Espirita'),
('Parque Veloso'),
('Parque Veredas'),
('Parque Vila Maria'),
('Parque Vila Prudente'),
('Parque Vitoria'),
('Pedreira'),
('Penha de Franca'),
('Perdizes'),
('Perus'),
('Pinheiros'),
('Piqueri'),
('Pirajussara'),
('Piraporinha'),
('Pirituba'),
('Planalto Paulista'),
('Polvilho'),
('Ponte Pequena'),
('Ponte Rasa'),
('Praia Azul'),
('Praia da Lagoa'),
('Praia do Leblon'),
('Praia Paulistinha'),
('Praias Paulistanas'),
('Promorar Vila Maria'),
('Protendit'),
('Quarta Parada'),
('Quinta da Paineira'),
('Rancho Geraldo'),
('Raposo Tavares'),
('Real Parque'),
('Recanto Alegre'),
('Recanto Ana Maria'),
('Recanto Campo Belo'),
('Recanto das Andorinhas'),
('Recanto dos Sonhos'),
('Recanto Frei Damiao'),
('Recanto Marisa'),
('Recanto Monte Alegre'),
('Recanto Paraiso'),
('Recanto Santo Antonio'),
('Recanto Verde do Sol'),
('Republica'),
('Residencial Morumbi'),
('Residencial Sol Nascente'),
('Residencial Taipas'),
('Residencial Vilela'),
('Retiro Morumbi'),
('Rio Bonito'),
('Rio Pequeno'),
('Riviera Paulista'),
('Rolinopolis'),
('Sacoma'),
('Santa Amelia'),
('Santa Cecilia'),
('Santa Efigenia'),
('Santa Etelvina'),
('Santa Ines'),
('Santa Maria'),
('Santa Teresinha'),
('Santana'),
('Santo Amaro'),
('Sao Domingos'),
('Sao Joao Climaco'),
('Sao Judas'),
('Sao Lucas'),
('Sao Mateus'),
('Sao Miguel Paulista'),
('Sao Salvador'),
('Sapopemba'),
('Saude'),
('Se'),
('Sete Praias'),
('Siciliano'),
('Sitio Areiao'),
('Sitio Barrocada'),
('Sitio Boa Vista'),
('Sitio Botuquara'),
('Sitio Bufalo'),
('Sitio Canela Branca'),
('Sitio Caraguata'),
('Sitio Cocaia'),
('Sitio da Figueira'),
('Sitio do Mandaqui'),
('Sitio do Morro'),
('Sitio do Piqueri'),
('Sitio Itaberaba I'),
('Sitio Itaberaba II'),
('Sitio Laredo'),
('Sitio Matsumura'),
('Sitio Morro Grande'),
('Sitio Pinheirinho'),
('Sitio Ponderosa'),
('Sitio Represa'),
('Sitio Tapera'),
('Sitio Vale Verde'),
('Socorro'),
('Sumare'),
('Sumarezinho'),
('Super Quadra Morumbi'),
('Taipas'),
('Tatuape'),
('Terceira Divisao'),
('Terceira Divisao de Interlagos'),
('Tremembe'),
('Tres Cruzes'),
('Tucuruvi'),
('Tuparacoera'),
('Umarizal'),
('Usina Piratininga'),
('Valo Velho'),
('Varzea da Barra Funda'),
('Varzea de Baixo'),
('Veleiros'),
('Vila ABC'),
('Vila Acre'),
('Vila Adalgisa'),
('Vila Ademar'),
('Vila Agua Funda'),
('Vila Agueda'),
('Vila Aimore'),
('Vila Alabama'),
('Vila Alba'),
('Vila Albano'),
('Vila Albertina'),
('Vila Alexandria'),
('Vila Almeida'),
('Vila Alpina'),
('Vila Alteza'),
('Vila Alzira'),
('Vila Amalia (Zona Leste)'),
('Vila Amalia (Zona Norte)'),
('Vila Amelia'),
('Vila America'),
('Vila Americana'),
('Vila Ana Claudia'),
('Vila Ana Rosa'),
('Vila Anadir'),
('Vila Analia'),
('Vila Anastacio'),
('Vila Andes'),
('Vila Andrade'),
('Vila Angelica'),
('Vila Angelina'),
('Vila Anglo Brasileira'),
('Vila Anhanguera'),
('Vila Antonieta'),
('Vila Antonina'),
('Vila Antonio'),
('Vila Antonio dos Santos'),
('Vila Aparecida'),
('Vila Aparecida Ivone'),
('Vila Apoena'),
('Vila Araguaia'),
('Vila Arapua'),
('Vila Arcadia'),
('Vila Arco Iris'),
('Vila Aricanduva'),
('Vila Arriete'),
('Vila Arruda'),
('Vila Augusto'),
('Vila Aurea'),
('Vila Aurora'),
('Vila Aurora (Zona Norte)'),
('Vila Ayrosa'),
('Vila Azevedo'),
('Vila Babilonia'),
('Vila Baby'),
('Vila Bancaria'),
('Vila Bancaria Munhoz'),
('Vila Bandeirantes'),
('Vila Barbosa'),
('Vila Barreto'),
('Vila Baruel'),
('Vila Basileia'),
('Vila Bauab'),
('Vila Beatriz'),
('Vila Bela'),
('Vila Bela Alianca'),
('Vila Bela do Sapopemba'),
('Vila Bela Vista (Zona Norte)'),
('Vila Bela Vista (Zona Sul)'),
('Vila Belo Horizonte'),
('Vila Bertioga'),
('Vila Bianca'),
('Vila Boacava'),
('Vila Bom Jardim'),
('Vila Bonilha'),
('Vila Bonilha Nova'),
('Vila Borges'),
('Vila Botoni'),
('Vila Bozzini'),
('Vila Brasil'),
('Vila Brasilandia'),
('Vila Brasilia (Zona Sul)'),
('Vila Brasilina'),
('Vila Brasilio Machado'),
('Vila Bruna'),
('Vila Buarque'),
('Vila Buenos Aires'),
('Vila Butanta'),
('Vila Cachoeira'),
('Vila Cachoeirinha'),
('Vila Caicara'),
('Vila Caiuba'),
('Vila Caju'),
('Vila California'),
('Vila California(Zona Sul)'),
('Vila Calu'),
('Vila Campanela'),
('Vila Campestre'),
('Vila Campo Grande'),
('Vila Canero'),
('Vila Capela'),
('Vila Caraguata'),
('Vila Carbone'),
('Vila Cardoso'),
('Vila Cardoso Franco'),
('Vila Carioca'),
('Vila Carlos de Campos'),
('Vila Carmem'),
('Vila Carmosina'),
('Vila Carolina'),
('Vila Carrao'),
('Vila Castelo'),
('Vila Castro'),
('Vila Catupia'),
('Vila Cavaton'),
('Vila Caxambu'),
('Vila Celeste'),
('Vila Centenario'),
('Vila Central'),
('Vila Chabilandia'),
('Vila Chalot'),
('Vila Charlote'),
('Vila Chavantes'),
('Vila Chica Luisa'),
('Vila Chuca'),
('Vila Cisper'),
('Vila Clara'),
('Vila Clarice'),
('Vila Claudia'),
('Vila Clelia'),
('Vila Clementino'),
('Vila Cleonice'),
('Vila Comercial'),
('Vila Conceicao'),
('Vila Conde do Pinhal'),
('Vila Congonhas'),
('Vila Constanca'),
('Vila Continental'),
('Vila Corberi'),
('Vila Cordeiro'),
('Vila Cosmopolita'),
('Vila Costa Melo'),
('Vila Cristalia'),
('Vila Cruz das Almas'),
('Vila Cruzeiro'),
('Vila Cruzeiro Novo'),
('Vila Cunha Bueno'),
('Vila Curuca'),
('Vila da Paz'),
('Vila da Saude'),
('Vila Dalila'),
('Vila Dalva'),
('Vila Damaceno'),
('Vila Danubio Azul'),
('Vila Darli'),
('Vila das Belezas'),
('Vila das Merces'),
('Vila Deodoro'),
('Vila Dinorah'),
('Vila Dionisia'),
('Vila Diva (Zona Leste)'),
('Vila Diva (Zona Norte)'),
('Vila Divina Pastora'),
('Vila do Bosque'),
('Vila do Castelo'),
('Vila do Encontro'),
('Vila do Sol'),
('Vila Dom Jose'),
('Vila Dom Pedro I'),
('Vila Dom Pedro II'),
('Vila Domitila'),
('Vila Dona Augusta'),
('Vila Dona Meta'),
('Vila Dona Sara'),
('Vila Dorna'),
('Vila dos Andradas'),
('Vila dos Andrades'),
('Vila dos Minerios'),
('Vila dos Palmares'),
('Vila dos Remedios'),
('Vila Doutor Eiras'),
('Vila Duarte'),
('Vila Ede'),
('Vila Elba'),
('Vila Eliana'),
('Vila Elias Nigri'),
('Vila Elida'),
('Vila Eliete'),
('Vila Elisio'),
('Vila Elvira'),
('Vila Elze'),
('Vila Ema'),
('Vila Emir'),
('Vila Erna'),
('Vila Ernesto'),
('Vila Escolar'),
('Vila Esmeralda'),
('Vila Espanhola'),
('Vila Esperanca'),
('Vila Ester'),
('Vila Ester (Zona Norte)'),
('Vila Euthalia'),
('Vila Fachini'),
('Vila Fanton'),
('Vila Fatima'),
('Vila Fazzeoni'),
('Vila Feliz'),
('Vila Fernandes'),
('Vila Fiat Lux'),
('Vila Fidalgo'),
('Vila Fidelis Ribeiro'),
('Vila Firmiano Pinto'),
('Vila Formosa'),
('Vila Franca'),
('Vila Franci'),
('Vila Francos'),
('Vila Friburgo'),
('Vila Frugoli'),
('Vila Fukuya'),
('Vila Gabriel'),
('Vila Gea'),
('Vila Germaine'),
('Vila Germinal'),
('Vila Gertrudes'),
('Vila Gil'),
('Vila Gilda'),
('Vila Giordano'),
('Vila Gomes'),
('Vila Gomes Cardim'),
('Vila Gouveia'),
('Vila Graciosa'),
('Vila Granada'),
('Vila Graziela'),
('Vila Guaca'),
('Vila Guacuri'),
('Vila Guaraciaba'),
('Vila Guarani(Zona Leste)'),
('Vila Guarani(Zona Sul)'),
('Vila Guedes'),
('Vila Guilherme'),
('Vila Guilhermina'),
('Vila Guiomar'),
('Vila Gumercindo'),
('Vila Gustavo'),
('Vila Hadad'),
('Vila Hamburguesa'),
('Vila Hebe'),
('Vila Helena'),
('Vila Heliopolis'),
('Vila Herminia'),
('Vila Homero'),
('Vila Hungaresa'),
('Vila Icarai'),
('Vila Ida'),
('Vila Iguacu'),
('Vila Imperio'),
('Vila Inacio'),
('Vila Inah'),
('Vila Independencia'),
('Vila Independente'),
('Vila Indiana'),
('Vila Industrial'),
('Vila Inglesa'),
('Vila Invernada'),
('Vila Iolanda II'),
('Vila Iolanda(Lajeado)'),
('Vila Iorio'),
('Vila Ipojuca'),
('Vila Iracema'),
('Vila Irene'),
('Vila Irmaos Arnoni'),
('Vila Isa'),
('Vila Isabel'),
('Vila Isolina Mazzei'),
('Vila Itaberaba'),
('Vila Itaim'),
('Vila Ivg'),
('Vila Ivone'),
('Vila Jaci'),
('Vila Jacui'),
('Vila Jaguara'),
('Vila Jaguari'),
('Vila Jaragua'),
('Vila Joaniza'),
('Vila Joao Batista'),
('Vila Judith'),
('Vila Julio'),
('Vila Julio Cesar'),
('Vila Jurema'),
('Vila Jussara'),
('Vila Klaunig'),
('Vila Lageado'),
('Vila Lais'),
('Vila Lar Nacional'),
('Vila Leme'),
('Vila Leonor'),
('Vila Leopoldina'),
('Vila Libanesa'),
('Vila Lisboa'),
('Vila Liviero'),
('Vila Londrina'),
('Vila Lourdes'),
('Vila Lucia'),
('Vila Lucia Elvira'),
('Vila Luzimar'),
('Vila Macedopolis'),
('Vila Madalena'),
('Vila Mafra'),
('Vila Malvina'),
('Vila Mangalot'),
('Vila Mara'),
('Vila Maracana'),
('Vila Marari'),
('Vila Marcelo'),
('Vila Marconi'),
('Vila Margareth'),
('Vila Margarida'),
('Vila Maria'),
('Vila Maria Alta'),
('Vila Maria Baixa'),
('Vila Maria Eugenia'),
('Vila Maria Luisa'),
('Vila Maria Trindade'),
('Vila Maria Zelia'),
('Vila Mariana'),
('Vila Marieta'),
('Vila Marilena'),
('Vila Marina'),
('Vila Maringa'),
('Vila Mariza Mazzei'),
('Vila Marte'),
('Vila Mascote'),
('Vila Matias'),
('Vila Matilde'),
('Vila Mazzei'),
('Vila Medeiros'),
('Vila Mendes'),
('Vila Mercedes'),
('Vila Mesquita'),
('Vila Miami'),
('Vila Michelina'),
('Vila Minerva'),
('Vila Mira'),
('Vila Mirante'),
('Vila Miriam'),
('Vila Mirim'),
('Vila Missionaria'),
('Vila Moderna'),
('Vila Moinho Velho'),
('Vila Monte Alegre'),
('Vila Monte Santo'),
('Vila Monumento'),
('Vila Moraes'),
('Vila Moreira'),
('Vila Morgadouro'),
('Vila Morro Grande'),
('Vila Morse'),
('Vila Morumbi'),
('Vila Nair'),
('Vila Nancy'),
('Vila Narciso'),
('Vila Nascente'),
('Vila Natal'),
('Vila Natalia'),
('Vila Neila'),
('Vila Nelson'),
('Vila Nhocune'),
('Vila Nilo'),
('Vila Nilva'),
('Vila Nina'),
('Vila Nitro Operaria'),
('Vila Nitro Quimica'),
('Vila Nivi'),
('Vila Noca'),
('Vila Nogueira'),
('Vila Norma'),
('Vila Nossa Senhora Aparecida'),
('Vila Nossa Senhora da Conceicao'),
('Vila Nossa Senhora do Retiro'),
('Vila Nova'),
('Vila Nova Alba'),
('Vila Nova Cachoeirinha'),
('Vila Nova Caledonia'),
('Vila Nova Carolina'),
('Vila Nova Conceicao'),
('Vila Nova Curuca'),
('Vila Nova das Belezas'),
('Vila Nova Galvao'),
('Vila Nova Jaragua'),
('Vila Nova Manchester'),
('Vila Nova Mazzei'),
('Vila Nova Parada'),
('Vila Nova Pauliceia'),
('Vila Nova Perus'),
('Vila Nova Pirajussara'),
('Vila Nova Sao Miguel'),
('Vila Nova Savoia'),
('Vila Nova Teresa'),
('Vila Nova Uniao'),
('Vila Nova Utinga'),
('Vila Nova York'),
('Vila Odete'),
('Vila Olga'),
('Vila Olimpia'),
('Vila Olinda'),
('Vila Oratorio'),
('Vila Paiva'),
('Vila Palmeiras'),
('Vila Paranagua'),
('Vila Parque Jabaquara'),
('Vila Patrimonial'),
('Vila Pauliceia'),
('Vila Paulina'),
('Vila Paulista'),
('Vila Paulista I'),
('Vila Paulista II'),
('Vila Paulistana'),
('Vila Paulistania'),
('Vila Paulo Silas'),
('Vila Pedra Branca'),
('Vila Pedrosa'),
('Vila Pedroso'),
('Vila Penteado'),
('Vila Pereira Barreto'),
('Vila Pereira Cerca'),
('Vila Perus'),
('Vila Piaui'),
('Vila Picinin'),
('Vila Pierina'),
('Vila Piracicaba'),
('Vila Pirajussara'),
('Vila Pirituba'),
('Vila Pita'),
('Vila Plana'),
('Vila Polopoli'),
('Vila Pompeia'),
('Vila Ponte Rasa'),
('Vila Popular'),
('Vila Portugal'),
('Vila Portuguesa'),
('Vila Prado'),
('Vila Praia'),
('Vila Prel'),
('Vila Primavera'),
('Vila Primeiro de Outubro'),
('Vila Princesa Isabel'),
('Vila Progredior'),
('Vila Progresso (Zona Leste)'),
('Vila Progresso (Zona Norte)'),
('Vila Progresso (Zona Sul)'),
('Vila Prudente'),
('Vila Quarto Centenario'),
('Vila Quintana'),
('Vila Ramos'),
('Vila Rancho Alegre'),
('Vila Raquel'),
('Vila Re'),
('Vila Regente Feijo'),
('Vila Regina'),
('Vila Reis'),
('Vila Remo'),
('Vila Renato (Zona Leste)'),
('Vila Renato (Zona Norte)'),
('Vila Represa'),
('Vila Ribeiro de Barros'),
('Vila Rica'),
('Vila Rio Branco'),
('Vila Robertina'),
('Vila Rodrigues'),
('Vila Romana'),
('Vila Romano'),
('Vila Romero'),
('Vila Roque'),
('Vila Rosa'),
('Vila Rosa Molla'),
('Vila Rosaria'),
('Vila Roschel'),
('Vila Roseira II'),
('Vila Rosina'),
('Vila Rubi'),
('Vila Rui Barbosa'),
('Vila Sabrina'),
('Vila Salete'),
('Vila Sampaio'),
('Vila Santa Catarina'),
('Vila Santa Clara'),
('Vila Santa Cruz'),
('Vila Santa Cruz (Zona Leste)'),
('Vila Santa Delfina'),
('Vila Santa Edwiges'),
('Vila Santa Eulalia'),
('Vila Santa Ines'),
('Vila Santa Isabel'),
('Vila Santa Lucia'),
('Vila Santa Maria'),
('Vila Santa Teresa (Zona Leste)'),
('Vila Santa Teresa (Zona Sul)'),
('Vila Santa Teresinha'),
('Vila Santa Terezinha (Zona Norte)'),
('Vila Santa Virginia'),
('Vila Santana'),
('Vila Santista'),
('Vila Santo Antonio'),
('Vila Santo Estefano'),
('Vila Santo Estevam Reis'),
('Vila Santo Estevao'),
('Vila Santo Henrique'),
('Vila Santos'),
('Vila Sao Camilo'),
('Vila Sao Domingos'),
('Vila Sao Francisco'),
('Vila Sao Geraldo'),
('Vila Sao Jose'),
('Vila Sao Jose (Cidade Dutra)'),
('Vila Sao Jose (Guaianazes)'),
('Vila Sao Jose (Ipiranga)'),
('Vila Sao Jose (Itaim Paulista)'),
('Vila Sao Judas'),
('Vila Sao Luis(Zona Oeste)'),
('Vila Sao Nicolau'),
('Vila Sao Paulo'),
('Vila Sao Pedro'),
('Vila Sao Sebastiao'),
('Vila Sao Silvestre'),
('Vila Sao Silvestre (Zona Leste)'),
('Vila Sao Vicente'),
('Vila Sapopemba'),
('Vila Sara'),
('Vila Savoy'),
('Vila Seabra'),
('Vila Sergio'),
('Vila Serralheiro'),
('Vila Silva Teles'),
('Vila Silveira'),
('Vila Silvia'),
('Vila Simone'),
('Vila Sinha'),
('Vila Siqueira (Zona Leste)'),
('Vila Siqueira (Zona Norte)'),
('Vila Sirene'),
('Vila Siria'),
('Vila Socorro'),
('Vila Sofia'),
('Vila Sol'),
('Vila Solange'),
('Vila Sonia'),
('Vila Souza'),
('Vila Stela'),
('Vila Suica'),
('Vila Sulina'),
('Vila Suzana'),
('Vila Taiau'),
('Vila Talarico'),
('Vila Taquari'),
('Vila Teresinha'),
('Vila Tiradentes'),
('Vila Tolstoi'),
('Vila Tramontano'),
('Vila Uberabinha'),
('Vila Uniao (Zona Leste)'),
('Vila Uniao(Zona Norte)'),
('Vila Universitaria'),
('Vila Ursulina'),
('Vila Valdemar'),
('Vila Vanda'),
('Vila Vasconcelos'),
('Vila Vera'),
('Vila Verde'),
('Vila Vermelha'),
('Vila Vessoni'),
('Vila Virginia'),
('Vila Vitorio Mazzei'),
('Vila Yara'),
('Vila Zat'),
('Vila Zefira'),
('Vila Zelina'),
('Vila Zilda'),
('Vila Zulmira'),
('Vista Alegre');